### ISSUE TITLE
[Bug]: Background colour a bit weird when using with tmux

### ISSUE THREAD

**Issue by zawedcvg** [akinsho/bufferline.nvim#207]
### What happened?

The issue is that when using bufferline with tmux, the current tab is highlighted in a weird fashion.
![Screenshot from 2021-08-28 12-28-14](https://user-images.githubusercontent.com/46929289/131206124-5dfdebb5-5ba4-4e37-aedf-ab740f1c7bc2.png)

### What did you expect to happen?

Expected behaviour: the normal bufferline current tab colour.

### Additional Information

...

**Comment by akinsho** [comment]
@zawedcvg this is because by default the current buffer users an `bold italic` highlight, and it seems your tmux has not been set up to correctly draw bold italic text. Your two options are to fix italic highlights inside tmux in your config (I don't remember how I did this off the top of my head so you will need to google it) or to disable them by setting current buffer highlights (the exact group names are in the help docs)

**Comment by zawedcvg** [comment]
managed to enable bold italic highlight and now it works like a charm. Thanks!
