### ISSUE TITLE
Recent changes to BufferLineGoToBuffer

### ISSUE THREAD

**Issue by lcrockett** [akinsho/bufferline.nvim#210]
I was used to using `BufferLineGoToBuffer` based on the ordinal number of the buffer, regardless of it's visual position. However in commit `d343bc322e00e9b21bcb9b3c8bf6a989b64a92a2` this behaviour changed to jumping to a buffer based on it's visual position. It does make sense from one perspective, however it seems cumbersome to keep counting the how "many'th" buffer you'd like to jump to and only then picking it using `BufferLineGoToBuffer` (for times when `BufferLinePick` seems a tad bit slower then \<leader\>+\<number\>).

Is this change in behaviour permanent or does that functionality still remain in one way or another ?

Cheers on keeping up with the continuous stream of improvements to an excellent bufferline plugin.

**Comment by akinsho** [comment]
@lcrockett the change was intentional and didn't offer an alternative because I'm trying to manage the proliferation of options in this plugin. Ultimately, I don't want there to be a bunch of options around this. The main issue is that counting visible buffers is an overhead, ideally there'd be an option to show these but atm that'd be complicated to do. In the short/medium term, there is a way round this.

You can create your own command using the `require'bufferline'.go_to_buffer(number, absolute)` absolute is a boolean that determines whether to use the absolute buffer position or the visible/relative one. You can then define a command similar to the existing one that does this.

**Comment by lcrockett** [comment]
Perfect, works like a charmadillo. Cheers !

**Comment by stumash** [comment]
@lcrockett mind posting the code you wrote? I want this too

**Comment by lcrockett** [comment]
@stumash I don't have much code to show you, i've incorporated @akinsho's recommendation in my `which-key` configuration. See below:

```lua
    ['1'] = { '<cmd>lua require("bufferline").go_to_buffer(1, true)<cr>', 'which_key_ignore' },
    ['2'] = { '<cmd>lua require("bufferline").go_to_buffer(2, true)<cr>', 'which_key_ignore' },
    ['3'] = { '<cmd>lua require("bufferline").go_to_buffer(3, true)<cr>', 'which_key_ignore' },
    ['4'] = { '<cmd>lua require("bufferline").go_to_buffer(4, true)<cr>', 'which_key_ignore' },
    ['5'] = { '<cmd>lua require("bufferline").go_to_buffer(5, true)<cr>', 'which_key_ignore' },
    ['6'] = { '<cmd>lua require("bufferline").go_to_buffer(6, true)<cr>', 'which_key_ignore' },
    ['7'] = { '<cmd>lua require("bufferline").go_to_buffer(7, true)<cr>', 'which_key_ignore' },
    ['8'] = { '<cmd>lua require("bufferline").go_to_buffer(8, true)<cr>', 'which_key_ignore' },
    ['9'] = { '<cmd>lua require("bufferline").go_to_buffer(9, true)<cr>', 'which_key_ignore' },
```
