### ISSUE TITLE
Any way to sort buffers so that .h/.hpp files end up next to the appropriately named .c/.cpp file?

### ISSUE THREAD

**Issue by rickyelopez** [akinsho/bufferline.nvim#211]
if the files are named correctly (i.e. MyCoolModule.c => MyCoolModule.h), would be really cool if we could sort the buffer such that related files are next to one another.

I searched through closed issues but didn't notice a relevant one, sorry if I missed it!

**Comment by akinsho** [comment]
@rickyelopez this plugin exposes an option called `sort_by` which a user can specify as a function which is can be used to sort buffers. You can use this function to figure a way to get your desired outcome. Maybe check the extensions of the buffers or something. I don't work with either of those filetypes regularly, so can't help specifically.

**Comment by rickyelopez** [comment]
Okidoke, I'll try to mess with that if I ever get a chance, thanks!

**Comment by akinsho** [comment]
Going to close this out now since I believe this can be solved in userland using a sort function, I'd rather not go down the rabbit hole of doing it myself since I don't have a use case or the time to implement an example but if you do work it out please post it back here as someone else might find it useful
