### ISSUE TITLE
[Bug]: vim's sessions handling

### ISSUE THREAD

**Issue by 0xRZ** [akinsho/bufferline.nvim#226]
### What happened?

Hi, thank you for the plugin, it makes nvim more convenient. But there is an issue that vim's mksession creates additional empty buffers while using this plugin.

To Reproduce:
With vim-plug, init.vim:
```vim
call plug#begin()
Plug 'akinsho/bufferline.nvim'
call plug#end()

lua << EOF
require("bufferline").setup{}
EOF
```
Steps:
1. Create file1 and file2
2. Open nvim with file1
3. In nvim run :new file2
4. move file2 to new tab with :tab sp
5. :mksession!
6: :qa
7: reopen nvim and run :source Session.vim

As you will see there will be 3 buffers restored instead of 2, with the additional [No Name] empty buffer, not previously created.

![image](https://user-images.githubusercontent.com/46892933/133811679-489f5438-1755-47ad-9b3b-88f0e5f6acc7.png)

### What did you expect to happen?

Correct restorment of a session.

### Additional Information

nvim --version
NVIM v0.6.0-dev+289-g1ec3d3719
Build type: Release
LuaJIT 2.1.0-beta3

bufferline.nvim commit: be5866b77c713d92cf3d383a387bec1d55e3f798

**Comment by akinsho** [comment]
Hi @0xRZ, I don't believe this is this plugin tbh, since the commit you mention doesn't actually change how this plugin handles the buffer list. In all likelihood you have `tabs` as part of your `sessionopts` and there is a bug in nvim where having tabs creates new blank buffers. I don't recall the nvim issue off hand but this plugin doesn't have the ability to actually *create* buffers it only reads the ones that already exist. You can confirm this by running `:ls` to show that there is actually a new `[No name]` buffer

**Comment by 0xRZ** [comment]
Well this one new blank [No name] buffer does not appear after session restore with plain init.vim file, only when im using this plugin. In both cases sessionopts includes tabpages by default

**Comment by akinsho** [comment]
@0xRZ I'm not sure if I understand, if you use a plain init.vim you won't be able to see buffers anyway so in the case of a blank init.vim you'd never expect to see this no name buffer.

**Comment by akinsho** [comment]
The most important point at @0xRZ is if your `:ls` command contains a listed no name buffer since that essentially proves that the buffer came from vim. This plugin only reads the state from vim, so it's not really possible for it to show buffers that doesn't exist in vim since that's where the data comes from for the UI

**Comment by 0xRZ** [comment]
@akinsho Oh yeah sorry, my fault. ```:ls``` contains that noname blank buffer in both cases, guess i will make bugreport to nvim.

**Comment by akinsho** [comment]
@0xRZ I think https://github.com/neovim/neovim/pull/15062 PR was an attempt to port a fix that maybe should have fixed it, the original vim patch was https://github.com/vim/vim/commit/d39e275b57493f9e25e1b62f84810571eee30cf4. Although I don't know if those specifically target tabs in sessions, but I've had to turn that option off for this reason but don't have the time to shepherd an nvim issue myself atm.

**Comment by 0xRZ** [comment]
@akinsho but ```hidden``` option is essential, if i remember correctly without it buffers may be destroyed when using LSP and jumping to definition that is contained in another buffer for example.

**Comment by akinsho** [comment]
@0xRZ it is essential and soon to be default if not already default in nvim master, I'm not suggesting removing it, not sure if the issues or patch suggest that either. I only added those links for reference

**Comment by akinsho** [comment]
Gonna close this out since it relates to upstream behaviour and can't be solved here.
