### ISSUE TITLE
open buffer in new split?

### ISSUE THREAD

**Issue by ExpandingMan** [akinsho/bufferline.nvim#229]
There's probably already a way of doing this, but it's still not apparent to me.  I'd like to have the ability to open buffers in new splits (or existing splits other than the one I'm on) using the same numerical designations as `bufferline.go_to_buffer`.

Is there a relatively easy way of doing this already?  If not, it seems like it would make a nice feature.

**Comment by akinsho** [comment]
@ExpandingMan there are a few different ways to handle this. You can set a click command so that clicking a tab opens it in a split e.g. I have
```lua
config = {
   right_mouse_command = 'vert sbuffer %d',
}
```
In my dotfiles so that the right mouse opens a buffer in a split
otherwise you can use the `require'bufferline'.buf_exec` api to do something like
```lua
function _G.open_split_buf()
  require'bufferline'.buf_exec(visible_buf_number, function(buf, all_visible)
   vim.cmd(string.format("vert sbuffer %d", buf.id))
  end
end
```
Then create a mapping with the above function

**Comment by ExpandingMan** [comment]
Cool, thanks!  Feel free to close.
