### ISSUE TITLE
Insert new buffer after current one

### ISSUE THREAD

**Issue by andytsan** [akinsho/bufferline.nvim#232]
Hi, great plugin!

Is there a way to configure it to insert the newly opened buffer to immediately after the current one?

I've found that opening a new buffer, inserts it at the end of the buffer list. The default behaviour of barbar.nvim for example is to insert the buffer after the current.

Thanks!

**Comment by akinsho** [comment]
Hi @andytsan,

Thanks, there is currently no way to do this. I'm not sure how easy or hard this will be to add since unlike barbar this plugin uses the buffer list from vim +/- any sorting a user applies rather than prioritising it's own internal state of buffers which this would need, I'll leave it open as a feature request.

**Comment by mgokbulut** [comment]
I would really like this functionality too

**Comment by nyngwang** [comment]
I would really like this functionality too

**Comment by akinsho** [comment]
Closing this out as this is now implemented on the `dev` branch and will make it out to the main branch once that's fully tested.

**Comment by akinsho** [comment]
fixed by #342

**Comment by nyngwang** [comment]
> Closing this out as this is now implemented on the dev branch and will make it out to the main branch once that's fully tested.

Thank you so much! I was busy and didn't notice this update, let me try it now!
