### ISSUE TITLE
allow disable by filetype

### ISSUE THREAD

**Issue by max397574** [akinsho/bufferline.nvim#250]
Could you add an option to disable by filetype?

**Comment by akinsho** [comment]
@max397574 you can accomplish this in vim already by using the `showtabline` setting and changing it in an autocommand e.g.
```vim
autogroup TablineVisiblity
  au!
  autocmd BufEnter if &filetype == '<FILETYPE_NAME>' | set showtabline=0 | elseif !&showtabline | set showtabline=2 endif
augroup END
```
This is an untested example to illustrate the idea, you can tweak this to your needs in your own config. I won't however add this to the plugin itself since I don't leave it's necessary or desirable.
