### ISSUE TITLE
[Bug]: attempt to index field 'fn' (a nil value)

### ISSUE THREAD

**Issue by Unknown-User2** [akinsho/bufferline.nvim#260]
### What happened?

The issue is that...
when i run nvim with the vimscript way to use it it give me the error on startup `attempt to index field 'fn' (a nil value)`

### What did you expect to happen?

Expected behaviour
i expected it to not give this error

### Additional Information

...

**Comment by akinsho** [comment]
@Unknown-User2 this unfortunately doesn't enough information, what version of neovim are you on? the `fn` field is a key on the vim object inside all recent versions of neovim. It seems likely that you are not on a recent neovim version since I can't reproduce this issue

**Comment by Unknown-User2** [comment]
my nvim is version 0.4.4

**Comment by Unknown-User2** [comment]
i updated to 0.5.1 and now its giving me the error `bufferline/colors.lua:71: attempt to index global 'bit' (a nil value)`

**Comment by akinsho** [comment]
@Unknown-User2 this is likely because you do not have the correct version or any version of luajit installed. Please ensure it is installed, and you should be fine. You also need to verify that you are running lua 5.1 on your system with nvim depending on how it was installed. In any case, I think it's safe to say this is more of a nvim + dependencies version issue than a bufferline issue.

**Comment by akinsho** [comment]
@Unknown-User2 I don't know how to help, since the bit package should be available using luajit and is required for this plugin. I know that there are some issues with some distros regarding the versions of certain packages they use. To be clear it's a very specific version of luajit that nvim requires not just any version, but as I said the problem isn't something I can solve but something relating to a potential version issue on your system

**Comment by akinsho** [comment]
Going to close this out as there's been no response. I believe the root cause here is not having a version of luajit where `bit` is available, which means that neovim has likely been compiled with the wrong luajit version.
