### ISSUE TITLE
[Bug]: wrong window when Chadtree is opened during switch

### ISSUE THREAD

**Issue by Mte90** [akinsho/bufferline.nvim#267]
### What happened?

If I open the chadtree sidebar (https://github.com/ms-jpq/chadtree/), next I switch the tab the buffer is opened in the chadtree buffer instead on the central one.
If the chadtree buffer is closed there are no issues of course.

### What did you expect to happen?

Buffer switch on the right panel and not the first one.

### Additional Information

```
require'bufferline'.setup{
    options = {
        diagnostics = "nvim_lsp",
        diagnostics_indicator = function(count, level, diagnostics_dict, context)
            if context.buffer:current() then
                return ''
            end

            return ''
        end,
        offsets = {
            {
                filetype = "CHADtree",
                text = "File Explorer",
                highlight = "Directory",
                text_align = "left"
            }
        }
    }
}
```

**Comment by akinsho** [comment]
@Mte90 unfortunately I can't understand what isn't working correctly at all from this issue. To be clear this plugin *just shows buffers* it doesn't manage windows or control how buffers are opened. It doesn't have *any* code to control how your windows behave.

**Comment by Mte90** [comment]
Uhm so the offsets parameter is not useful.
Usually buffer switchers have parameters to avoid those situation, I mean if I have a "sidebar" of a specific plugin it won't be get touch when I switch to another buffer and only the center panel is used.

**Comment by akinsho** [comment]
@Mte90 the `offsets` parameter works as intended, but I don't understand what you are trying to do or what situation is occurring. Can you post a video or GIF which shows what this issue is?

**Comment by Mte90** [comment]
https://user-images.githubusercontent.com/403283/143286481-034833ca-4c9f-4c04-8eda-a8f888f53a61.mp4

As you asked :-)

**Comment by akinsho** [comment]
So I don't necessarily see the specific problem, but I'll point out some things I noticed.

The offset isn't working, and this is probably because you are using the wrong value for `filetype` for chadtree. I don't use this plugin, but that's probably why the offset doesn't show as expected. You need to open that buffer and get the correct filetype using something like `:echo &filetype` when inside the buffer and use that in your config instead.

Second, you are doing some clicking of the buffer tabs, but I'm guessing you imagined that the buffers would open in the bigger window instead of the smaller window. This is a fundamental difference with nvim versus GUIs like vscode. All windows are essentially the same, all that happens when you click a buffer is we run `:edit <bufname>` if you are inside the small window, then that is where it will open. There is no such thing as a sidebar window, that doesn't exist in nvim, so it won't open the buffer in some other window just because there is a small one on the left for chadtree. Nvim doesn't recognize that window as being special, so doesn't treat it as such.

**Comment by Mte90** [comment]
The filetype is the right one instead for the second point make sense, I am wondering if it is possible to add a settings to use the last buffer window or the central one.
In this one should fix as there are tons of plugins that use sidebars.

**Comment by akinsho** [comment]
@Mte90 I think that should be handled in the user's config or by using the custom open command with another plugin or a custom function. As I've mentioned in quite a few issues lately this plugin provides *UI* not buffer or window management. If a user wants to handle how windows are opened or closed they should add a custom click command which implements this as I won't add that here since that IMO is another plugin's responsibility and a bunch of code that I don't want to write

**Comment by Mte90** [comment]
Thanks for the help, I will look for another tab plugin.
