### ISSUE TITLE
[Feature request] dynamic tab size depending on name length

### ISSUE THREAD

**Issue by DanielCardonaRojas** [akinsho/bufferline.nvim#268]
Is it possible to have dynamic tab size depending on file name and maybe have max_tab_size option ?

**Comment by akinsho** [comment]
Hi @DanielCardonaRojas,

this came up quite a while ago as a suggestion from Barbar's author, interestingly enough. Personally I don't like the aesthetic and uniformity is very important to me. I think similar to web browsers or vscode's tabs etc. I think each tab should have a uniform size. I would accept and help guide a well implemented PR to add this functionality, but I personally won't add it myself as it would involve spending my free time on functionality that I don't really personally agree with, which isn't something I'm keen on 🤷🏿

**Comment by gerazov** [comment]
Maybe if it's a single buffer it can be the full name?

**Comment by akinsho** [comment]
>  I would accept and help guide a well implemented PR to add this functionality, but I personally won't add it myself

This comment still stands as far as this issue is concerned. If someone wants this enough, they should please feel free to raise a working PR. I don't think it should be implemented as an edge case, though, i.e. only if single buffer. This should be all or nothing. A user sets this option then all tabs have dynamic widths as long as their content or truncated to a max size 🤷🏿

**Comment by akinsho** [comment]
This was done in #533 it's currently only in dev but will be released soon.
