### ISSUE TITLE
[Bug]: 'scroll' option

### ISSUE THREAD

**Issue by 0xRZ** [akinsho/bufferline.nvim#269]
### What happened?

Hello, seems like when using this plugin i can not set `'scroll'` option. When i open any file `:verbose set scroll?` always outputs 
``` 
scroll=16
        Last set from changed window size
````
Even though i have `set scroll=10` set in my .vimrc, `autocmd BufEnter * set scroll=10` also does not help. And i would really like to be able to change scroll option.

**Comment by akinsho** [comment]
@0xRZ as far as I can tell this isn't something specific to this plugin but rather to neovim. I personally have never used this setting but looking at `:help scroll` it says
```
						*'scroll'* *'scr'*
'scroll' 'scr'		number	(default: half the window height)
			local to window
	Number of lines to scroll with CTRL-U and CTRL-D commands.  Will be
	set to half the number of lines in the window when the window size
	changes.  This may happen when enabling the |status-line| or
	'tabline' option after setting the 'scroll' option.
	If you give a count to the CTRL-U or CTRL-D command it will
	be used as the new value for 'scroll'.  Reset to half the window
	height with ":set scroll=0".
```
Specifically, it mentions that whenever the window changes size, it is set to half the window size of the window. Regarding how to fix it, I don't really know, since this seems to be standard vim behaviour. Perhaps you can try another autocommand like `WinEnter` or `BufWinEnter` but it seems like using a tabline at all will cause this issue regardless of whether you use this plugin. The only thing that I'd see as different is that this plugin doesn't actually set the tabline till *after* the `VimEntered` autocommand, so it sets the tabline *after* your config has run, so you might want to fiddle with delaying setting that option 🤷🏿

**Comment by 0xRZ** [comment]
@akinsho Thank you for the explanation. Yeah so i found out `autocmd WinScrolled` works for setting scroll option and it persists.
