### ISSUE TITLE
Show buffers based on (vim)tab

### ISSUE THREAD

**Issue by marwan38** [akinsho/bufferline.nvim#270]
Hello, I tried searching but could not find an answer, or a discussion, for the subject of this issue.

I sometimes open (vim) tabs to maintain context of what i'm doing. IE: Project is open in a single tab with all it's buffers, then I may have another vimtab that contains my notes and misc.

When I have more than a single tab open, the buffers in the bufferline are shared by both tabs. Is this by design? Is there a way to only display buffers by active tab?

**Comment by akinsho** [comment]
Hi @marwan38 there are actually a lot of issues relating to vim tabs, but the specific issue you are describing about buffers being shared by tabs is a neovim issue/misunderstanding of vim tabs that is super common. Vim tabs show *windows* not buffers. Vim tabs *do not know anything about buffers*, people often try to restrict buffers to a specific tab, but vim does not support this concept. A tab is simply a way of visualising windows, not buffers. There are a constellation of hacks that people try to get this behaviour, but this plugin doesn't do any of that because it's about buffers primarily not tabs and I don't personally believe in trying to work around this behaviour which is native to nvim.

**Comment by marwan38** [comment]
> Hi @marwan38 there are actually a lot of issues relating to vim tabs, but the specific issue you are describing about buffers being shared by tabs is a neovim issue/misunderstanding of vim tabs that is super common. Vim tabs show _windows_ not buffers. Vim tabs _do not know anything about buffers_, people often try to restrict buffers to a specific tab, but vim does not support this concept. A tab is simply a way of visualising windows, not buffers. There are a constellation of hacks that people try to get this behaviour, but this plugin doesn't do any of that because it's about buffers primarily not tabs and I don't personally believe in trying to work around this behaviour which is native to nvim.

As a work around to what I'm trying to achieve, I think sorting buffers by relevant tab would be good enough. The minimal tab UI that displays on the top right is beautiful, and does exactly what I want.

It's all good then, thanks for taking the time to look at this thread and reply. I'll close this for now.
