### ISSUE TITLE
Replace deprecated `vim.lsp.diagnostic.get_all` call(s)

### ISSUE THREAD

**Issue by hood** [akinsho/bufferline.nvim#271]
https://github.com/akinsho/bufferline.nvim/blob/463637a3ac86dcaacbcd47aa608f53aaad749696/lua/bufferline/diagnostics.lua#L54

Is using `vim.lsp.diagnostic.get_all`, which has been deprecated. `vim.diagnostic.get()` should be used instead.

**Comment by pinpox** [comment]
Can confirm, running into it aswell.

**Comment by AlexisFinn** [comment]
+1 also running into this with the latest release-0.6 
```
NVIM v0.6.1-dev+666-g2cd272dec
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/alexis/Applications/neovim/build/config -I/home/alexis/Applications/neovim/src -I/home/alexis/Applications/neovim/.deps/usr/include -I/usr/include -I/home/alexis/Applications/neovim/build/src/nvim/auto -I/home/alexis/Applications/neovim/build/include
```

**Comment by AlexisFinn** [comment]
Hello.
I'm still experiencing the problem and with a quick investigation on the merged fix (https://github.com/akinsho/bufferline.nvim/pull/272), it seems the culprit is the `is_nightly` test in diagnostics.lua.
```
+local is_nightly = utils.is_truthy(fn.has("nvim-0.7"))
+local is_valid_version = utils.is_truthy(fn.has("nvim-0.5"))
```
It only tests for `0.7` but I can confirm this this problem also appears in `0.6`.

**Comment by akinsho** [comment]
@AlexisFinn can you clarify what problem you are actually seeing on 0.6. I'm running 0.6 and don't see any clear issues. The diagnostics still show up as expected. This issue never really clarified what was actually wrong i.e. what behaviour was incorrect so I don't know what you are experiencing.

**Comment by akinsho** [comment]
To clarify nvim-0.6 still has access to `vim.lsp.diagnostic.get_all` tbh it could also be migrated to use `vim.diagnostic.get` but this API is not stable and seems to be changing on master so I would rather not have to work around different behaviours of the same function based on version. This issue makes me think that I might be best served restricting this plugin or at least this feature to the latest stable nvim because I'd rather not have to constantly keep up to date with all the unstable changes on nvim master all the time especially if the dev team are (as is their perogative, breaking things on occasion)

**Comment by AlexisFinn** [comment]
@akinsho the main issue is having the error pop up incessantly in the status bar, it's mainly a nuisance instead of a functional problem, but it just doesn't feel right to have an incessant error message that is "normal".
![2021-12-15-160210_772x93_scrot](https://user-images.githubusercontent.com/7420883/146210792-a3822438-f8e5-42c1-af6d-1609eae9d732.png)

I get that you don't want to have to update the code each time the api decides to change, 
Maybe have an option to disable diagnostics in the buffer "tabs" so that the function is not called at all ?

**Comment by AlexisFinn** [comment]
Oh wait... the option does exist ? I'm supposing `diagnostics = false` will avoid this. I feel a bit silly now. Should read the docs first, sorry.

**Comment by akinsho** [comment]
@AlexisFinn I'm not seeing this deprecation warning at all, are you definitely on `nvim-0.6` can you paste the output of `:version` or `nvim -v` (in the CLI) here?

**Comment by AlexisFinn** [comment]
@akinsho Ok, my mistake. 
I build nvim from source and was using the `release-0.6` Branch instead of the `v0.6.0` Tag.
Once I checkout the proper version the warning no longer shows up.

So it's all good, thank you very much for your time.
