### ISSUE TITLE
[Feature Request] Hide buffers if tabs are open.

### ISSUE THREAD

**Issue by lifer0se** [akinsho/bufferline.nvim#278]
As the title says, would there be a way to only show buffers if no tabs are open?

For my workflow at work, I'm dealing with 7 buffers at a time, 4 in a grid, then 2 on a vsplit on a tab and the last on another tab. I would like to hide all the buffers and only keep the tabs visible but then be able to go back to showing buffers when I close the tabs.

Would that be possible?
Thanks in advance :)

**Comment by akinsho** [comment]
@lifer0se that currently isn't possible. The plugin only really shows buffers and doesn't provide any really special tab visibility functionality aside from the minimal tab indicators. There are several closed and one open tab related issue in #195 . As I've mentioned there I'm happy to accept PRs to visualise tabs but will not implement this myself, at least not in the near future

**Comment by lifer0se** [comment]
Would it be possible to just hide all buffers if tabs are open?? There's a custom filter option and I assume I could get the number of tabs and filter out all buffers if  there are tabs open. I tried a few thing but none of them work. 

Is it possible to filter out buffers like that??

**Comment by akinsho** [comment]
@lifer0se you can use the custom filter to filter out buffers based on whatever logic you want. In your case you can maybe check the number of open tabs and use that to decide whether or not to show any buffers. The specific logic will be up to you since you will need to test this logic against your desired outcome. The help docs show an example which shows how to filter out buffers based on the tab count. You can also check the `vim.api` for functions that tell you how many tabs are open and use that for your logic

**Comment by lifer0se** [comment]
Perfect! Found the solution in he :h document. This works:


    custom_filter = function(buf)
      local tab_num = vim.fn.tabpagenr()
      if tab_num > 1 then
          return false
      else
          return true
      end
    end

Thanks for your help!!

**Comment by rubenmate** [comment]
Now that is possible to switch between tabpages and buffers, could it be possible to apply it to filtering?
I mean something like this:
custom_filter = function(buf)
  local tab_num = 0
  for _ in pairs(vim.api.nvim_list_tabpages()) do tab_num = tab_num + 1 end
  if tab_num > 1 then
      -- Change to tabpages
      return false
  else
      -- Change back to buffers
      return true
  end
end
