### ISSUE TITLE
Only Show buffers in the active Tabs

### ISSUE THREAD

**Issue by ahmed-rezk-dev** [akinsho/bufferline.nvim#288]
How to Only Show buffers in the active Tabs and Not all Buffers?

**Comment by akinsho** [comment]
@ahmed-rezk-dev there are some previous issues that discuss how to do this that you can find if you search past issues, there isn't any functionality provided by default but users can solve this in their configuration using the `custom_filter` option. [This issue](https://github.com/akinsho/bufferline.nvim/issues/278) appears to be similar to what you are looking for.

**Comment by tristone13th** [comment]
> @ahmed-rezk-dev there are some previous issues that discuss how to do this that you can find if you search past issues, there isn't any functionality provided by default but users can solve this in their configuration using the `custom_filter` option. [This issue](https://github.com/akinsho/bufferline.nvim/issues/278) appears to be similar to what you are looking for.

Will it influence the behavior of :bn and :bp?

**Comment by akinsho** [comment]
If you are using a custom filter or sorting buffers using bufferline it is recommended you use the provided `BufferLineCycleNext` and `BufferLineCyclePrev` commands since there is no way to make the builtin `bn` and `bp` respect the order this plugin shows as nvim doesn't provide anyway to do that

**Comment by tristone13th** [comment]
> If you are using a custom filter or sorting buffers using bufferline it is recommended you use the provided `BufferLineCycleNext` and `BufferLineCyclePrev` commands since there is no way to make the builtin `bn` and `bp` respect the order this plugin shows as nvim doesn't provide anyway to do that

I'm wondering if there is a solution for binding the buffer to the tab which first accesses it, then we can treat tabs as separate projects, or is there a way to determine the buffer list of the current tab so we can just show them rather than all the buffers. (The definition of buffer list is the first time assess it).

**Comment by akinsho** [comment]
@tristone13th so it's important to first clarify that vim tabs are not designed to relate to specific buffers at all but rather they are a collection of windows. This means that any attempts to relate a tab to specific buffers will essentially hacks to work around vim's native behaviour. Personally I don't want to maintain a bunch of code to hack around native vim behaviour. This is a common request though but I think better requested upstream in neovim. Realistically though they are very unlikely to implement a change like this. I think as a community we just need to accept that tabs don't represent projects or workspaces

**Comment by tristone13th** [comment]
> @tristone13th so it's important to first clarify that vim tabs are not designed to relate to specific buffers at all but rather they are a collection of windows. This means that any attempts to relate a tab to specific buffers will essentially be hacks to work around vim's native behaviour. Personally I don't want to maintain a bunch of code to hack around native vim behaviour. This is a common request though but I think better requested upstream in neovim. Realistically though they are very unlikely to implement a change like this. I think as a community we just need to accept that tabs don't represent projects or workspaces

You are right, thanks for the detailed explanations, I think I may need to leave the vim native tabs untouched and find another concept such as session or workspace to achieve my workflow.

**Comment by akinsho** [comment]
I personally use sessions to mirror the workspace workflow using using rmagatti's session plugin so when I open vim from a specific directory it works all the buffers I was last working on and I use tmux windows to house different projects in different directions

**Comment by akinsho** [comment]
Going to close this out since it was a duplicate originally and has been answered.

**Comment by joehannes** [comment]
I just wanted to leave my solution as a comment here.
I also use rmagattis session plugin and since each tabpage can have it's own `cwd` set, you can use tabpages for different projects. To me this is useful when I for example:
* have the backend and frontend in different tabpages
* have a third party/helper repo/project opened in a different tabpage (that is evolving along the project)
* I tweak my nvim-cfg and do want to see my updates reflected in something else than lua right there
...
You can always not set the `cwd` of a new tabpage and so for example use some tabpages as layouts ... the vastness of possibilities, wow :-)

So anyway, I use the session-plugin of rmagatti combined with telescope-project to quickly set a `cwd` on a new tabpage, but disable automatic `cwd`-setting on buffer-selection (this way it wouldn't be the root .git/project folder and this little function wouldn't work)

Here's the function:
```lua
custom_filter = function(buf_number)
	if not not vim.api.nvim_buf_get_name(buf_number):find(vim.fn.getcwd(), 0, true) then
		return true
	end
end
```

Also, and by the way, the modified/sort-by function given in the README doesn't work for me @akinsho ... at least I did have that impression back in the day (a few months) and this is what I came up with instead:

```lua
sort_by = function(buffer_a, buffer_b)
	local mod_a = ((vim.loop.fs_stat(buffer_a.path) or {}).mtime or {}).sec or 0
	local mod_b = ((vim.loop.fs_stat(buffer_b.path) or {}).mtime or {}).sec or 0
	return mod_a > mod_b
end
```
