### ISSUE TITLE
Go to last buffer

### ISSUE THREAD

**Issue by danymat** [akinsho/bufferline.nvim#310]
Hello, 

I'm currently remapping my keys to use bufferline:

```lua
vim.keymap.set("n", "<Leader>bn", ":BufferLineCycleNext<CR>")
vim.keymap.set("n", "<Leader>bb", ":BufferLineCyclePrev<CR>")
vim.keymap.set("n", "<Leader>bd", ":bd<CR>")
vim.keymap.set("n", "<Leader>b&", ":BufferLineGoToBuffer 1<CR>")
vim.keymap.set("n", "<Leader>bé", ":BufferLineGoToBuffer 2<CR>")
vim.keymap.set("n", '<Leader>b"', ":BufferLineGoToBuffer 3<CR>")
vim.keymap.set("n", "<Leader>b'", ":BufferLineGoToBuffer 4<CR>")
vim.keymap.set("n", "<Leader>b(", ":BufferLineGoToBuffer 5<CR>")
vim.keymap.set("n", "<Leader>b§", ":BufferLineGoToBuffer 6<CR>")
vim.keymap.set("n", "<Leader>bè", ":BufferLineGoToBuffer 7<CR>")
vim.keymap.set("n", "<Leader>b!", ":BufferLineGoToBuffer 8<CR>")
vim.keymap.set("n", "<Leader>bç", ":BufferLineGoToBuffer 9<CR>")
vim.keymap.set("n", "<Leader>bé", ":blast<CR>")
```

And I want to have a similar mapping of `:blast`, to use in Bufferline.
Something like `:BufferLineGotoBuffer -1`, or `:BufferLineGoToLastBuffer` (and respectively `:BufferLineGoToFirstBuffer`).
What do you think ?

**Comment by akinsho** [comment]
Hi 👋🏿,

Tbh I'm generally kind of against adding more commands, they're probably the thing I get asked to add the most, though they always seem quite specific to each user's workflow. Trying to go to the first or last buffer in the bufferline seems like a very rough way to navigate buffers. Could just be me, but if the buffer is visible you can presumably use the count, otherwise surely first or last is kind of a random guess and a user is better served using something like telescope.

In any event I don't feel strongly enough about it either way, I'd happily accept a PR adding it but am very unlikely to add it myself since I can't really envision the use case personally (/more importantly am quite busy atm so am not currently working on features for any of my plugins)

**Comment by tobealive** [comment]
> I'd happily accept a PR adding 

I take you by the word 😊. I found myself in situations where I missed that feature.
But I definitely have empathy for not bloating the code base with commands that are very specific to a users workflow. Rather providing a API that the users can add all they need themselves.

The PR just adds one line and allows to pass -1 to the `go_to_buffer` function. 
#471
