### ISSUE TITLE
Question: How to Close Current/Visible Buffer Only through Command (?)

### ISSUE THREAD

**Issue by ZN0N15** [akinsho/bufferline.nvim#311]
I've been reading through the README for a while and I've noticed that there seems to be no option or command to Close the Current/Visible Buffer, and its only done through clicking the Close button on the bufferline itself. The only commands/options available are `BufferLineCloseRight` (closes the buffer to the right of the current buffer) `BufferLineCloseLeft` (closes the buffer to the left of the current buffer) and `BufferLinePickClose` (choosing which buffers to close). I've been wanting to do a keybind that just quickly closes the Current/Visible Buffer Only, but there doesn't seem to be an option/command for me to bind to do that. Other similar Tabline plugins such as [barbar.nvim](https://github.com/romgrk/barbar.nvim) do seem to have that option. Does bufferline.nvim not have that or am I just missing something?

**Comment by akinsho** [comment]
@ZN0N15 closing the current buffer is a straightforward as using the builtin buffer deletion command `:bdelete!` this doesn't require a custom command from this plugin or anything like that. Unless I'm misunderstanding what you are trying to do.

It's also important to note that barbar embeds a *whole buffer management plugin* called vim-bbye in it's codebase which is why it provides a lot of buffer management commands. This plugin *does not manage buffers* a user should instead install an accompanying buffer management plugin if they want/need to rather than it being embedded in a plugin that is just for visuals IMO

**Comment by Ahanaf-Ether** [comment]
@akinsho I love this plugin! I would love to know how to close buffers properly i had a bind: nnoremap <C-q> :q!<CR> to close anything including tabs. But after using this i notice it does close the window but the old windows remain visible, is this a bug? Or am i just to dumb to figure out whats wrong?

**Comment by akinsho** [comment]
@Ahanaf-Ether closing a buffer in vim is done with the `:bdelete` command you can read more about this using `:help bdelete`. To be clear opening and closing buffers/tabs isn't really an issue specific to this buffer but something general to vim.

**Comment by ZN0N15** [comment]
Thank you! Seems I didn't read through all the readme docs properly and missed this.

**Comment by Ahanaf-Ether** [comment]
@akinsho it works with ":bdelete" but doesnt work as a bind, probably a vim issue, Anyways thanks.

**Comment by Ahanaf-Ether** [comment]
oh damn, i figured i was messing it up by having this binding:
"inoremap <C-q> <Esc>:q!<cr>" and 
of course: 
autocmd BufNewFile * startinsert
autocmd VimEnter * if empty(expand("%")) | startinsert | endif
autocmd VimEnter * if getfsize(expand("%")) == 0 | startinsert | endif

**Comment by Ahanaf-Ether** [comment]
And damn clean code my man! will you teach me some day how you code like that?
