### ISSUE TITLE
[Bug]: Error when opening project buffers of same file type

### ISSUE THREAD

**Issue by patchworkCode** [akinsho/bufferline.nvim#318]
### What happened?

Getting a very strange error when I open up a new buffer that's the same file type in this one particular project.

I'm not sure whether it's bufferline or something on my end because the plugin otherwie works fine. 

If anything, just understanding what the error is saying would be nice

![image](https://user-images.githubusercontent.com/62321034/151437089-e4340e4d-fad4-45c6-91bb-db3879ec4bef.png)

### What did you expect to happen?

Opens buffer with no issues

### Additional Information

...

**Comment by patchworkCode** [comment]
Here is the project repository: https://github.com/patchworkCode/github_battle

If possible, cloning it, then opening up popular.js then a new buffer with battle.js can replicate the issue, thanks!

**Comment by akinsho** [comment]
@patchworkCode I can't see the entire stack trace in your screenshot, ideally could you post the text rather than a screenshot. In any case, it looks like the `user_indicator` function is erroring which is just an alias for a user defined `diagnostics_indicator` presumably you have set this value to a function, and it is erroring. Can you please remove that configuration option (and all other, really, and use just a minimal setup) and see if the same issue recurs without that setting specified?

If that resolves the issue, then you likely have some syntax error in that function, and you should look into fixing it.

**Comment by patchworkCode** [comment]
Sorry about that!

Yes it seems to be `diagnostics_indicator` but it's strange since I just copied and pasted the suggested implimentation from the documentation.

```lua
require("bufferline").setup{
  options = {
    diagnostics = "nvim_lsp",
    diagnostics_update_in_insert = false,
    diagnostics_indicator = function(count, level, diagnostics_dict, context)
      local s = " "
      for e, n in pairs(diagnostics_dict) do
        local sym = e == "error" and " "
          or (e == "warning" and " " )
        s = s .. n .. sym
      end
      return s
    end,
    separator_style = "slant"
  }
}
```

**Comment by akinsho** [comment]
@patchworkCode I don't see that example anywhere in the documentation? it's not in the help text or the README, the `sym` variable logic is essentially incorrect since it doesn't have a final fallback close, so it looks like it's possible that it returns `sym = false` which is not a string. I'd suggest having a look at that logic more closely. The examples are anyway just supposed to give users an idea of how things work, it's expected that each user will figure out for themselves how they want their diagnostic indicator to work if they don't want to use the default.

**Comment by patchworkCode** [comment]
Don't worry, I fixed it by having a look at your dotfiles, and copying the implementation you had there! Thanks for the help
