### ISSUE TITLE
[Help Wanted] Is there any way to filter files by git status?

### ISSUE THREAD

**Issue by hexh250786313** [akinsho/bufferline.nvim#325]
How can I use `custom_filter` to filter files by git status. I want my bufferline only show the git changed files and current file. I think it requires some other plugins like `fugitive` or `coc-git`, but I do not really konw how to do that.

**Comment by akinsho** [comment]
Hi @hexh250786313

 this isn't really something you could solve trivially. You'd need to go down the rabbit hole to figure this one out yourself since I don't really have an answer. My advice would be to find a plugin that exposes the list of changed git files synchronously, so it doesn't block nvim. Then you'd only show buffers with the matching name or id. This is already a big oversimplification since you'd need to figure out which plugin does this and how you can get this list. Sorry that I can't help anymore.

**Comment by hexh250786313** [comment]
@akinsho Thanks your advice! I will have a try.

**Comment by akinsho** [comment]
@hexh250786313 I'm going to close this out but if you figure out  away to do this please feel free to post your solution here for posterity 🙏🏿
