### ISSUE TITLE
[Bug]: `BufferLineCycle` commands don't recongize groups

### ISSUE THREAD

**Issue by Yohe-Am** [akinsho/bufferline.nvim#332]
### What happened?

The issue is that when groups are hidden as seen for the `Docs` group in following image... 

![image](https://user-images.githubusercontent.com/56622350/157262197-6cb86369-5047-4717-9b91-316eb947b774.png)

...the `BufferLineCycle` commands aren't able to cycle to buffers inside of this group.

### What did you expect to happen?

`BufferLineCycle` command to unhide the group and cycle to a buffer inside the group as per their orderings.

### Additional Information

`bnext` and `bprevious` commands don't face this issue,

### commit

7451dfc97d28e6783dbeb1cdcff12619a9323c98

**Comment by akinsho** [comment]
@Yohe-Am this is by design. The idea of hiding groups is that you can skip over them while you cycle, so if you have a bunch of tests and don't want to have to cycle through like 20 test buffers you can hide them. If you want to raise a PR to add an option per group to behave differently I'd accept that PR, but currently this works as I intended for my use case.

**Comment by Yohe-Am** [comment]
Oh, I see. Thanks
