### ISSUE TITLE
[Feature Request] Indicators to show if a buffer is in a tab

### ISSUE THREAD

**Issue by ofseed** [akinsho/bufferline.nvim#356]
I think it would be very useful because I often close a buffer in a tab, but I forget the buffer is in another tab,
which causes the other tab to be changed beyond my expectations.
For example, this is the bufferline,
```
▎   plugins.lua    ▏  bufferline.lua   ▏
```
if `plugins.lua` is exist in tab 1, `bufferline.lua` is exist in tab 2, display like
```
▎   plugins.lua  ①  ▏  bufferline.lua ②  ▏
```
If `plugins.lua` is exist both in tab 1 and tab 2, `bufferline.lua` does not exist in every tab, display like
```
▎   plugins.lua  ①②  ▏  bufferline.lua   ▏
```
Hide the indicators when there's only one tab.

**Comment by akinsho** [comment]
@ofseed if you're willing to submit a PR for this functionality I can guide you on how to do it, it's an interesting idea but I currently have way too much to do to do this myself

**Comment by ofseed** [comment]
OK, I will try to implement it by myself, but I'm not familiar with the neovim plugin development, so it may take lots of time.

**Comment by akinsho** [comment]
I'm still open to a PR if you ever get round to raising one but I'm going to close this out because short of a PR from an interested party I'm likely not going to add this. What would be more interesting that this specific feature though would be allowing a custom area inside a buffer tab so users can add their own custom stuff like this by themselves
