### ISSUE TITLE
[Question] What is the highlighted group of diagnostics?

### ISSUE THREAD

**Issue by askfiy** [akinsho/bufferline.nvim#357]
I want Bufferline to look as much as possible to vscode.

When I focus on the current buffer, it looks normal:

![图片](https://user-images.githubusercontent.com/81478335/161419216-aa5c070e-6f8f-495a-a645-35b6985890c8.png)

When I focus on another buffer, its `bg` `fg` becomes weird:

![图片](https://user-images.githubusercontent.com/81478335/161419241-1bbd87c9-7215-4908-923f-3b662f6ce25e.png)

I'm wondering, how can I set the highlight group to make the diagnostics look normal when my focus is on other buffers.

I want its `fg` to change, but not its `bg`.

I read the `doc` carefully, but the problem is still not solved.

**Comment by akinsho** [comment]
@askfiy all the highlight groups are noted down in `:help bufferline-highlights`  the diagnostics correspond to the level of error you are seeing e.g. info, warning, error etc. I can't help debug these easily since it's easier for you to see exactly what type of error you are seeing.

Please read through the highlights section in details 🙏🏿 the highlight group you are looking for will be there
