### ISSUE TITLE
[Bug]: some highlights have changed recently

### ISSUE THREAD

**Issue by ikerurda** [akinsho/bufferline.nvim#368]
### What happened?

See the white bar separator:

<img width="474" alt="Screenshot 2022-04-09 at 11 28 19 PM" src="https://user-images.githubusercontent.com/45340417/162592494-65cd4b0e-44ae-494a-9fdf-d21ed8a58418.png">
<img width="474" alt="Screenshot 2022-04-09 at 11 28 22 PM" src="https://user-images.githubusercontent.com/45340417/162592496-961b5f68-df81-41fd-b23e-1c33fa626547.png">

### What did you expect to happen?

I was expecting no white bar separators:
<img width="474" alt="Screenshot 2022-04-09 at 11 36 35 PM" src="https://user-images.githubusercontent.com/45340417/162592516-d840bf67-aa31-49ad-a110-24c79b660881.png">
<img width="474" alt="Screenshot 2022-04-09 at 11 36 38 PM" src="https://user-images.githubusercontent.com/45340417/162592518-ee9ed68b-2ba3-4487-a95f-031bc7de1427.png">

### Additional Information

I'm currently using the theme [projekt0n/github-nvim-theme](https://github.com/projekt0n/github-nvim-theme), if the issue is related to that plugin I would appreciate you guide me to the desired highlight group (they currently are only setting BufferLineIndicatorSelected and BufferLineFill).
Thanks!

### commit

c703e8d

**Comment by akinsho** [comment]
@ikerurda so based on the above I don't really have enough information to help, the commit you reference wasn't about changing highlight groups, so I wouldn't expect anything there to have changed and nothing changed in my highlights. Can you confirm that if you revert the specific commit, the problem is fixed (i.e. it is caused by the commit you linked)? Can you confirm that this issue happens in other colorschemes (i.e. it is a problem specifically with this plugin)

**Comment by ikerurda** [comment]
I'm sorry, this has to do with `8f7e72f` not the commit I mentioned, my bad.
Sourcing manually the bufferline setup file after nvim is loaded fixes de highlight, so that makes me think this has to do with timing (?).
I also tried this with another colorscheme ([ellisonleao/gruvbox.nvim](https://github.com/ellisonleao/gruvbox.nvim)) as you suggested and worked fine...

**Comment by akinsho** [comment]
@ikerurda so that commit you referenced removed a janky optimization I tried to add awhile ago which deferred loading this plugin till after vim had started. It was an attempt to reduce the startup cost of this plugin, which is already basically negligible and was pointless in hindsight. I'm not sure why it should break anything unless a theme is setting colours late or something, frankly I don't really know without digging through their codebase which tbh I haven't got time to do.
