### ISSUE TITLE
[Bug]: ✗ Failed to update akinsho/bufferline.nvim

### ISSUE THREAD

**Issue by lpanebr** [akinsho/bufferline.nvim#375]
### What happened?

I get this error when running PackerUpdate

"✗ Failed to update akinsho/bufferline.nvim"

![image](https://user-images.githubusercontent.com/129185/163467365-fe4762f9-5fba-413a-af28-4a30020b818e.png)

### What did you expect to happen?

Regular success message

### Additional Information

...

**Comment by akinsho** [comment]
@lpanebr not sure if you figured this out already, but I renamed the main branch and packer is not able to deal with that. Your options are to reinstall the plugin or specify the branch as main in your config. I think a quick re-installation is better since you won't need to reset change the syntax of your packer use.

Apologies for the inconvenience will close this out as well now since that should be it
