### ISSUE TITLE
[Bug]: `slant` or `padded_slant` yield different colors on buffer line's background

### ISSUE THREAD

**Issue by tapyu** [akinsho/bufferline.nvim#382]
### What happened?

Setting `separator_style = "slant"` or `separator_style = "padded_slant"` produces odd color background on the buffer line.

![Screenshot from 2022-04-18 01-30-28](https://user-images.githubusercontent.com/22801918/163754682-dc5c4dcf-2cc4-48c6-8252-405797ab41d0.png)

### What did you expect to happen?

Expected behaviour is a buffer line background's color consistent with the rest of my `colorscheme`, as the `README.md` example:

![](https://user-images.githubusercontent.com/22454918/111992989-fec39b80-8b0d-11eb-851b-010641196a04.png)

### Additional Information

```
Terminal: alacritty
OS: Ubuntu 20.04.4 LTS x86_64
colorscheme: Duskfox (on the photo, but all colorschemes has the same bug)
NVIM v0.7.0
```

**Comment by akinsho** [comment]
@tapyu I can't reproduce this with my colorscheme, can you try another theme and report if you still see this issue?

**Comment by tapyu** [comment]
> @tapyu I can't reproduce this with my colorscheme, can you try another theme and report if you still see this issue?

What the name of your color scheme? All of my colorschemes have the same glitch

btw: theme=colorscheme, right? :laughing:

**Comment by akinsho** [comment]
@tapyu yes, the theme is equivalent to the colorscheme. It shouldn't be a matter of using my specific one, but I use `doom-one.nvim`. Anyway, it looks like the separator colour is being set to the same as the `TablineSel`. Have you changed any colours, are you seeing this behaviour in a minimally configured nvim. Can you try just loading only this plugin and your colorscheme with none of the rest of your config to see if there is something in your config causing this issue

**Comment by tapyu** [comment]
Yes, I can. This is the [link](https://github.com/tapyu/dotfiles/tree/bufferline-debug/nvim/.config/nvim) for the minimal nvim config. It only has literally `bufferline.nvim` and the `packer` itself as plugins.

If you cannot reproduce, maybe it is a constrainment in my terminal, which is `alacritty`...

**Comment by tapyu** [comment]
In this repo, I get this buffer line (with `separator_style = "padded_slant"`)

![Screenshot from 2022-04-18 08-41-17](https://user-images.githubusercontent.com/22801918/163803311-1ab3ca3a-f24a-4352-a659-10c65bb66181.png)

**Comment by tapyu** [comment]
In other colorschemes, you can notice that background color of the buffer line is sightly different, as shown here

![Screenshot from 2022-04-18 08-42-40](https://user-images.githubusercontent.com/22801918/163803499-1540c65a-0564-48a8-a3b6-a71d6bd7a5d8.png)

**Comment by akinsho** [comment]
@tapyu can you run a minimal vim without a specific repo e.g.
create a minimal file with only
```lua
vim.cmd('packadd bufferline.nvim')

require'bufferline'.setup({
	options = {
		separator_style = "padded_slant"
	}
})
```

Then do something like `nvim -u <Path/to/minimal> --noplugin` and test that way since that is a cleaner environment.

Regarding the slant highlight, it isn't supposed to be the same as it uses different colours for the background and the separator on purpose. The image in your previous comment is strange to me since only one buffer is slanted. Tbh the slant style won't work for all terminal emulators and as I mentioned in the README I can't fix every terminal emulator.

The issue in your first image seems to be that the highlight group that the separator depends on is a different colour than it should be. I don't know why that is but is likely related to the colorscheme which sets all the colours

**Comment by akinsho** [comment]
I just tried the `duskfox` theme, and it does the same for me, I looked at the code and the author is changing the highlights for this plugin on purpose which I recommend that colorscheme authors *do not do*, but some do anyway. This seems specific to that colorscheme and not this plugin though, so I would look to set the colours you want yourself looking at the help docs in `:h bufferline-highlights` or to change your theme.

**Comment by tapyu** [comment]
Here we are, a total clean `neovim` setup, only with `bufferline`

![Screenshot from 2022-04-18 08-57-28](https://user-images.githubusercontent.com/22801918/163804987-97ae91dd-9769-444c-99a8-80a6494ab04d.png)

**Comment by tapyu** [comment]
I've tried on the default Ubuntu's terminal and terminator. Same result.

**Comment by akinsho** [comment]
@tapyu that is not the default colorscheme for neovim I think, so I think it is loading a colorscheme anyway. As I mentioned above, please test out a few different colorscheme or change the highlights yourself in your config. I don't think this is a bug in the plugin

**Comment by tapyu** [comment]
I've tried different colorschemes, nothing worked out. . .

**Comment by akinsho** [comment]
@tapyu I'll revisit this later in the week when I have more free time. I think this is most likely a config issue since this issue is not reported commonly. What problem are you seeing with other colorschemes and can you link to the exact colorschemes with a screenshot of the issue you are seeing in each

**Comment by tapyu** [comment]
Well bro, actually I have one more... [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) screw up the colors highlighting when I write a modified file. That wrote file keep with correct highlighting, but all other new-opened file get a mess up highlighting.

I think maybe you are right. It could be some color problem on my computer. I am seriously thinking about rebooting all it (and even change the distro) just to see if this behavior disappear. I just opened this issue because, if there is some problem with your plugin, I wanna help you to identify it.

I will keep you in touch in case I reboot my machine...

**Comment by tapyu** [comment]
Now I am 100% sure there is some bug on your plugin. Just to let you know, I move from Ubuntu to Majanro. In a totally out-of-the-box terminal setting, I opened up `nvim` v0.7 with `~/.config/nvim/init.lua`

```lua
vim.cmd('packadd bufferline.nvim')
 
require'bufferline'.setup({
        options = {
                separator_style = "padded_slant"
        }
})
```

`bufferline.nvim'` is in `~/.local/share/nvim/site/pack/packer/`. And I get it

![image](https://user-images.githubusercontent.com/22801918/163918883-44829ca5-9070-4c9b-8444-dc204075ccdb.png)

Either your plugin has some issue or my `nvim` has some problem (I installed with `Appimage`.

**Comment by tapyu** [comment]
Same behavior with `nvim` v0.6.1 installed via `pacman`, so it is a problem with `bufferline`.

**Comment by akinsho** [comment]
@tapyu this plugin will not highlight things correctly with the default neovim colorscheme, the colour for the separator is derived from the `Normal` highlight group. If you run neovim minimally and run `:highlight Normal` you will see `Normal cleared`. The default "colorscheme" which is barely a colorscheme does not include a real background highlight, so this plugin cannot get anything to use as the separator colour.

What we need in this issue is to clarify what you are trying to achieve:
* The original issue that started this whole thing off is that duskfox does not look as expected. As I have clarified, this is because that plugin has manipulated this plugin's highlights.
* The default colorscheme doesn't look right -> this is because it provides very few actual highlight groups this plugin cans use to derive the colours it uses
* You mentioned that other colour schemes were broken, please provide screenshots/links to those colour schemes? Ultimately, if the authors have manipulated those highlights as well, there is nothing I can do about this.

**Comment by tapyu** [comment]
You are right, in the minimal configuration, `nvim` does have `Normal cleared`, which explains my screenshots. Now, in my normal config with the `darkplus` colorscheme (which as far as I know it is not a "default colorscheme which is barely a colorscheme"), I get the following picture

![image](https://user-images.githubusercontent.com/22801918/163940323-d4a1f549-4f71-4c5d-b96f-d070c43a0866.png)


The colorscheme that you've mentioned, `doom-one.nvim`, gives the following screenshot

![image](https://user-images.githubusercontent.com/22801918/163940558-eb2603e3-5153-4b76-9f2e-8f5bcb8fafbf.png)

Both have highlight groups, but the result diverges from the expected behavior (I do not know that these groups are enough or correct, anyway). But as you said

> Ultimately, if the authors have manipulated those highlights as well, there is nothing I can do about this.

So I think this issue is not a bug, but rather it is a limitation of the highlight group of the colorscheme, right? Thank you anyway.

**Comment by rodhash** [comment]
I was looking for something else and found this, situation similar to what I faced recently so leaving my 2 cents here:

I had similar issue while working on my own colorsheme and in my case I ended up changing one or two highlight groups, which might help regarding that strong white you got couple msg above:

https://user-images.githubusercontent.com/29671981/171524202-bc3e48ff-07be-414a-8784-de9b7632b414.mp4

I'm not sure but this seems to be a color scheme issue as well so if you're still trying to setup (or customize) this amazing plugin maybe this could help, or maybe not :)

**Comment by trevex** [comment]
As pointed out by @rodhash:

I was able to adapt the colors as follows:
```lua
vim.cmd [[hi BufferLineSeparator guifg=#504945]]
vim.cmd [[hi BufferLineSeparatorSelected guifg=#504945]]
vim.cmd [[hi BufferLineSeparatorVisible guifg=#504945]]
```

**Comment by Ryunaq** [comment]
Had the same problem too, as mentioned by @rodhash , doing this solved it
```lua
require('bufferline').setup({
  options = {
    mode = "buffers",
    separator_style = "slant",
  },
  highlights = {
    separator = {
      guifg = '#15161E',
    },
    separator_visible = {
      guifg = '#15161E',
    },
    separator_selected = {
      guifg = '#15161E',
    },
  },
})
```
