### ISSUE TITLE
[Feature request] allow emoji as the group name

### ISSUE THREAD

**Issue by nyngwang** [akinsho/bufferline.nvim#384]
I just tried the following config, but it always showed me only one group:

```lua
require('bufferline').setup {
  options = {
    close_command = nil,
    right_mouse_command = nil,
    enforce_regular_tabs = true,
    show_buffer_close_icons = false,
    groups = {
      items = {
        {
          name = "first",
          auto_close = false,
          matcher = function (b) return vim.api.nvim_buf_get_option(b, 'buflisted') end,
        },
        {
          name = "second",
          auto_close = false,
          matcher = function (b) return b.name:match('[No Name]') end,
        }
      }
    }
  }
}
```

Could you help me find out why this will only show either `first` or `second` but not both? I want to create a group for those `ungrouped` buffers in your config.

**Comment by akinsho** [comment]
@nyngwang a group of `buflisted` buffers doesn't really make sense. By default, all the buffers shown in the bufferline are *all* buflisted, that is the criteria that lets them into the bufferline so filtering for that is pointless. This seems related to your original issue on this repo. Please don't make several issues if you are just trying to solve one issue. Each issue opened in this repo creates more work for me, consumes more of my time.

**Comment by nyngwang** [comment]
@akinsho No, this is another issue. I just found that I cannot use emoji as the `name`. Changing the names solves my problem. But I recommend you also make emoji group name possible.

**Comment by akinsho** [comment]
@nyngwang please feel free to contribute a PR for any changes you would like to see added, I maintain this plugin on my own so just suggesting I should do X is not very helpful to me. What is the remaining issue in this particular issue, then, since I'm not sure where emoji comes into this issue. Is that the root cause for this issue?

**Comment by nyngwang** [comment]
> Is that the root cause for this issue?

@akinsho: Absolutely. I spent all day yesterday debugging the other possibilities, and finally found that all the groups re-appeared after I changed all the `name` to plain-text.

**Comment by akinsho** [comment]
@nyngwang group name's have to be alphanumeric, they are essentially the only identification a user has provided me for that group and are the basis of the internal ID for the group as well as the highlights for the group. Setting it to an emoji heavily breaks things, since there is no word to use as the id or basis for highlights. If you want to show an emoji I recommend using the `icon` field. Making emoji work would require *detecting* emoji and then generating some random word name for the user's group.

I personally don't think that the cost/benefit of this is nearly good enough, if you would like to contribute this change please look at

https://github.com/akinsho/bufferline.nvim/blob/f02e19bd29a27944e6bcc1e7a492fe07534b6630/lua/bufferline/groups.lua#L258

 And other parts in the file where name is reference, since you will likely need to substitute the user's emoji name with a word and only use the emoji for presentation purposes only.

I won't add this change myself since I feel that groups should have a proper name and the work of allowing them to not have a proper name is not worth it for me.

**Comment by nyngwang** [comment]
> [...] If you want to show an emoji I recommend using the `icon` field. [...]

This doesn't work, at least not the same as my expectation. It adds(prepend, to be precise) emoji to **every single file** in that group **and** the group tab. While I just want the emoji only for the tab.

I think the only part I cannot understand is why you decided to use the `name`, which is a string, as the id to identify each group. In my experience, internal ids are never meant to be readable. Even if you insist on this, I will still recommend adding a `display_name` just for display. This way people can put whatever they want in the tab. Anyway, I respect your design.

**Comment by akinsho** [comment]
@nyngwang the `name` field isn't used directly for an id but for the basis of the id e.g. `My Name` becomes `my-name` but the main reason for this is so the highlight groups are easily identifiable primarily for development e.g. `higlight MyNameHighlightlight` there is actually already a display name since the name you choose is copied over to the display name field as is. It's more that if you use emoji, there is no meaningful way to debug highlights or reasonably identify the field afterwards. It isn't the perfect design, but works well enough for most people. If you are interested in changing how this behaves to meet your needs as I've said I'm open to this
