### ISSUE TITLE
How to get the current list of buffers?

### ISSUE THREAD

**Issue by nyngwang** [akinsho/bufferline.nvim#404]
As title. I need to know the order of listed buffers.

**Comment by akinsho** [comment]
@nyngwang the plug-in doesn't expose the internal buffer list state. It's not intended to be used publicly. Why do you need to access it?

**Comment by nyngwang** [comment]
@akinsho Sometimes the `BufferLineCycleNext` doesn't move to the first buffer in the first group. Is this a feature?

**Comment by akinsho** [comment]
@nyngwang rather than exposing internal state and then having to maintain this API so that it is consistent even when I change the internal representation over time, I would much rather just fix whatever issue it is that you are seeing. That will be a lot less work in the long run, since I want the freedom to change the internal representation of bufferline buffers without having to worry about keeping whatever gets exposed up to date and having to worry about breaking changes and deprecations.

I don't understand the problem you are having clearly, can you please clarify with a GIF or an example of the exact issue you are seeing

**Comment by nyngwang** [comment]
The problem seems to be caused by the `auto_close = true` option of the only group I enabled. `BufferLineCycleNext` will not expand the closed group. Why this design?

**Comment by akinsho** [comment]
@nyngwang so this is by design it seems maybe there is a misunderstanding of `autoclose` I think if you are not sure of what it does then I recommend you do not use it.

The point of `auto_close` is that it should treat the buffers in that group as almost hidden you can toggle them open but by default they should be avoided during navigation.

The main reason I added that option is that sometimes there are files I open that I do not want to see or navigate too except once in a while duration an editing session. They should be out of the way. I think it is probably not the same use case you have, so you should remove that config option.

**Comment by nyngwang** [comment]
> [..] you should remove that config option.

Nope.

OK, I just confirmed that the behavior is the same as the Edge tab group. Thanks for your helps.

**Comment by tf42src** [comment]
Chipping in, I have the same request. Coming from a VSCode background (like many others I assume) it would be convenient to switch buffers by using C-<n>. I have successfully implemented a function (see [here](https://github.com/LazyVim/LazyVim/discussions/3746)) which does that, but it trips over when reordering the buffers, hence getting all buffers current position somehow would be amazing. [This](https://github.com/LazyVim/LazyVim/discussions/3766) lead me here.
