### ISSUE TITLE
[Question] Any way to use cterm colors instead of gui colors ?

### ISSUE THREAD

**Issue by girishji** [akinsho/bufferline.nvim#410]
To use highlight to configure colors terguicolors has to be enabled, which has a side effect of having to deal with new set of colors. any way we can use cterm limited colors to configure background for example? thanks for the plugin

**Comment by akinsho** [comment]
@girishji this has come up before in #326, in short, no it's not possible to use cterm colours. Primarily because when I wrote this plugin, I wanted to take say 6 base colours from nvim and then lighten or darken them to create the remaining parts of the colour palette for this plugin. I didn't/don't know how to lighten or darken cterm colours it might be easy or not 🤷🏾‍♂️ I don't use them, so I don't have any incentive to dig into it.

At this point, it would be a fair bit of work to go through the plugin and find all the places where hex colours are expected and allow them to take cterm colours. *I personally am not going to do this* because it's work that I won't personally see any value from. If someone who wants cterm colours is happy to do the work, and it doesn't break things for other people, then I'm happy to review a PR

**Comment by girishji** [comment]
I understand. It is not possible to lighten/darken colors in cterm with 16 color palette, but most terminals support 256 colors (first 16 are changeable by user, and the rest have fixed rgb values), and here it is possible. I think a plugin should not be doing any color modifications on its own. If user wants a different shade they will specify (in term-256 they have many shades of same color).

**Comment by akinsho** [comment]
@girishji I think we disagree about whether or not a plugin should be doing any modification to colours. That is a pretty big part of what this plugin does because I wanted the colouring to be automatic and so that if I change the colour scheme it should just work. I don't really agree at all that a plugin can't modify colours that it created for it's own usage.

**Comment by akinsho** [comment]
Also, it doesn't really make sense to leave it to the user to decide on the shade of the colour because that will basically mean that the user has to re-implement most of the functionality aesthetically of this plugin which would be a lot of work on the user side. Anyway, it's not really much to discuss because this is already the way that this plugin works

**Comment by girishji** [comment]
Thanks. I implemented cterm colors. I will send you PR. But some weirdness persists that I cannot explain. For example I can get ctermbg and ctermfg by Ex command, like :lua =vim.api.nvim_get_hl_by_name("Normal", false). But inside the plugin it gives garbage values (and pcall returns success, which is a bug in nvim). But some of the gui groups return correct color codes. If I switch vimscript functions (say vim.fn.synIDattr(vim.fn.synIDtrans(vim.fn.hlID(name)), attribute)) , same behavior except pcall(), when used, returns failure.
Of course, I can specify color codes directly (numbers 0-255) and bypass all this mess. Any idea? Are you setting something at terminal level that is interfering with its color codes?

**Comment by girishji** [comment]
In `colors.lua` `get_hex() you can have local success, `hl = pcall(vim.api.nvim_get_hl_by_name, name, true)`. If you pass `false` to this function it populates `ctermbg/fg` instead of `gui`. You can print out the values for say `PmenuSel` for instance and compare it with running the same function from command prompt.

**Comment by akinsho** [comment]
closed by #417
