### ISSUE TITLE
How is it possible to display two different fonts for the labels in the example

### ISSUE THREAD

**Issue by linqingyao** [akinsho/bufferline.nvim#421]
![QQ截图20220514145412](https://user-images.githubusercontent.com/83944508/168414606-69c7471a-a411-4141-b3c8-365cbc45b023.png)

I tried to read the responsibility point file, but unfortunately, I could not find the information available. Can you give me some directions and instructions? Thank you very much for your answer!

**Comment by akinsho** [comment]
@linqingyao this isn't really an issue for this plugin, so shouldn't really be opened as such. You can set different fonts to use for different font weights depending on the terminal editor you use. I use kitty and the config for that is
https://sw.kovidgoyal.net/kitty/conf/?highlight=font#fonts. Because the selected buffer is `bold` and I have configured a different font for bold text a different font is used there.

I'm going to close this out since it isn't an issue with this plugin

**Comment by linqingyao** [comment]
I see. Thanks again for all your hard work
