### ISSUE TITLE
`BufferLineMovePrev/Next` cannot swap with terminal buffers

### ISSUE THREAD

**Issue by nyngwang** [akinsho/bufferline.nvim#435]
As title. By the current implementation, they only work with normal buffers. So every buffer created by `:term` cannot be moved.

**Comment by akinsho** [comment]
@nyngwang if you'd like to see this change please feel free to raise a PR, by default this plugin only works on "normal" buffers and isn't really intended to operate on things like terminal buffers or other special buffers. I work under the assumption that people hide these buffers using `nobuflisted` if they do not, then I don't think there should be an expectation that they will work. Unless some user contributes that change. I hide all my terminal buffers, so this doesn't really impact me.

**Comment by nyngwang** [comment]
Philosophically, having an identity is important to any object. I'm currently trying to manipulate terminal buffers so that they can be seen just like normal buffers. Then, the most valuable benefit is that we don't need one more command or plugin for switching between multiple terminal buffers.

**Comment by akinsho** [comment]
@nyngwang I don't particularly agree or disagree with your argument, but as you have noted I created an entire other plugin based on my desired workflow for terminals, this works quite well for me. I personally have no incentive or reason to undertake this myself. I spend 90% of my free programming time maintaining nvim plugins instead of doing the things I want. This is not something that personally affects me, so I won't spend my free time on it. If you want to try, I can point you in the right direction. Lua is a very simple language, so I don't think this is a question of skill in Lua or anything like that.

**Comment by akinsho** [comment]
@nyngwang I'm going to close this out since I won't be tackling it but as I mentioned feel free to raise a PR if anyone else finds this and decides they want to tackle it they should also feel free to do so. I'm not against making this work I just wont do it myself.
