### ISSUE TITLE
[Feature Request]: Commands `BufferlineClose*` close modified buffers

### ISSUE THREAD

**Issue by Shatur** [akinsho/bufferline.nvim#438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Commands `BuferlineCloseLeft`, `BuferlineCloseRight` and `BufferlinePickClose` close modified buffers.

### What did you expect to happen?

I would expect to have an error message like "Unable to close modified buffer, add ! to override". So it would be nice to have the current behavior with bang and the expected behavior without it.

### Config

```lua
require("bufferline").setup({})
```

**Comment by akinsho** [comment]
@Shatur under the hood the API function used is called with force set to true which is my personal preference I don't mind there being a bang as an option to set this value but personally like the default behaviour and am not inclined to change it. If you would like to raise a PR to tweak this I'd be happy to review but I'm definitely not keen on adding this functionality myself since I already personally like the current behaviour

**Comment by akinsho** [comment]
This is now fixed on `dev` by #563
