### ISSUE TITLE
[Bug]: Bufferline gets transformed into UGLY white bar when I resize neovim to the lowest

### ISSUE THREAD

**Issue by siduck** [akinsho/bufferline.nvim#443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi @akinsho! Ive been facing this issue  :  

- Whenever I resize neovim window to the lowest , I get tons of bufferline errors and then bufferline gets transformed into an UGLY white bar :( 

## Behaviour 

https://user-images.githubusercontent.com/59060246/172033044-af6f1fa2-87e3-4e34-b8b7-beaf40d51b99.mp4

### What did you expect to happen? 

I dont want to see those errors & dont want bufferline to transform itself :c 

### Config

Was able to produce this issue with default bufferline config too so I dont think bufferline config's an issue.

**Comment by akinsho** [comment]
@siduck thanks for reporting the bug 👍🏿.

This should now be fixed in #444

FWIW, when reporting a bug I think it is good practice to avoid terms like "ugly" especially in caps. Primarily because you are reporting a technical issue and ugly is not a very useful term in this context, given that ugly is subjective and doesn't really describe what the maintainer should be looking for

Secondly the bufferline doesn't "transform itself" the plugin crashed and so the default native tabline replaced it, which is what happens if the tabline is enabled but crashes just FYI the white tabline is native to neovim by default and unrelated to this plugin.

**Comment by siduck** [comment]
@akinsho Really sorry if I sounded rude! Thx, its fixed now
