### ISSUE TITLE
Help: Difficulties setting tab offset using CHADTree

### ISSUE THREAD

**Issue by ZimmyLevi** [akinsho/bufferline.nvim#449]
Hi akinsho, I'm trying to set up bufferline.nvim with neovim, but I can't get the offset to work. I have also tried this with NERDTree.

Any help would be appreciated. I am using init.vim, with a Lua heredoc inside.

Thanks in advance, Zimmy.

**Comment by akinsho** [comment]
@ZimmyLevi as the template mentions you need to add your config (just the bufferline setup part) to any issue on this repo that you need help with otherwise I won't be able to help and will close this issue. It is most likely something not configured correctly. I **highly** recommend that you very carefully look at the layout of the config you are using and make sure things are set correctly in the correct place.

**Comment by ZimmyLevi** [comment]
I reinstalled everything and it's working now.
