### ISSUE TITLE
[Bug]: Typo in the readme.md file

### ISSUE THREAD

**Issue by Eezi** [akinsho/bufferline.nvim#476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The issue is that I tried to add **BufferLineCycleNext** and **BufferLineCyclePrev** to my config file but these commands didn't work. This was caused because these extra brackets, (see the image below):
<img width="876" alt="bufferline" src="https://user-images.githubusercontent.com/54830004/178660936-4fe82720-bf2c-427b-9fd9-bf3003a0f37b.png">

### What did you expect to happen?

Expected behaviour was that if I change the "b" from these lines to the "1" and "2", then I could jump "Next" tab from "1" and "Prev" tab from "2". After I removed these brackets they work as they should.
`nnoremap <silent>[b :BufferLineCycleNext<CR>`
`nnoremap <silent>b] :BufferLineCyclePrev<CR>`

### Config

" In your init.lua or init.vim
set termguicolors

nnoremap <silent>[1 :BufferLineCycleNext<CR>
nnoremap <silent>2] :BufferLineCyclePrev<CR>

lua << EOF
require("bufferline").setup{}
EOF

### Additional Information

Maybe this is not a typo and just my fault because I just started using neovim plugins and lua. I would like to fix this from the readme.md file if this is a real typo. :)

**Comment by akinsho** [comment]
@Eezi so it is a type but not the way you think, those are just example mappings they could be any keys a user likes, I'm not sure that I understand the 1,2 part of the expected behaviour I don't really know what that relates to or that that expectation is common. The general idea behind those keys is that they were similar to how https://github.com/tpope/vim-unimpaired sets mappings. The keys should be `[b` and `]b` so the second mapping is the wrong way round, in that way it is a typo.

**Comment by Eezi** [comment]
Okey, I think this was just my bad. I was little bit confused that you have to replace these both characters **[** and **b**. Because the **BufferLineMoveNext** and **BufferLineMovePrev** setup was so clear to me, that you just have to replace this `<mymap> ` with your own map. But to hear that I found real typo accidentally :D

**Comment by akinsho** [comment]
Fixed it on main now 👍🏿
