### ISSUE TITLE
[Feature Request]: ability to hide bufferline

### ISSUE THREAD

**Issue by Nexmean** [akinsho/bufferline.nvim#484]
### What?

It would be nice to have `BufferLineToggle/BufferLineHide/BufferLineShow` commands or field in config with predicate that tells plugin whenever to hide or to show itself.

### Why?

I want to hide bufferline in some cases:
- when it is tab for neogit
- when it is tab for gitview
- when there is only one buffer loaded

**Comment by akinsho** [comment]
@Nexmean this does not need to be built into the plugin because you can hide or show a tabline in neovim using `showtabline` please see `:h showtabline`, point 1, 2 can be done by just using an `ftplugin` file or an autocommand to `set showtabline=0` and reset it on `BufLeave`. Point 3 is already built into the plugin, and there is a configuration option for this.

In general, functionality like this that is well handled by neovim won't be added to the plugin, since it amounts to just more code to maintain that there isn't really a need for.

Apologies, but I'm going to close this out now since I don't think it requires an addition on this side and I often forget to tidy up my issues till much later if I don't do them at the time.

**Comment by Nexmean** [comment]
Thank you, I didn't know about `showtabline`.
