### ISSUE TITLE
[Bug]: E518: Unknown option: separator_style Press ENTER or type command to continue

### ISSUE THREAD

**Issue by OldWorldOrdr** [akinsho/bufferline.nvim#504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm sure I'm missing something stupid here, but I don't know where else to ask for help so I'm just gonna file a bug report. I'm very new to vim, and even newer to lua.  The option works as expected, I get slanted separators like I wanted, I just need to suppress the error message.

### What did you expect to happen?

Expected behaviour
It to not show this error

### Config

require("bufferline").setup{
options = {
    separator_style = "slant",
    },
}

(it doesn't show indentation here idk why, probably a github problem)
### Additional Information

...

### commit

idk i just installed so the latest ig

**Comment by OldWorldOrdr** [comment]
[init.vim.txt](https://github.com/akinsho/bufferline.nvim/files/9333351/init.vim.txt)
heres my entire init.vim if it helps

**Comment by akinsho** [comment]
Hi @OldWorldOrdr, so this option works as I can verify this locally by setting it myself, and it almost certainly is a configuration issue. In general a bug report isn't really ideal for this sort of thing since whilst I appreciate your predicament I maintain several plugins so having to help individual users with their configs is *very time-consuming* for me. Other than the indentation (which lua isn't sensitive to) this looks fine, so I don't know why you are seeing this issue, and it's probably related to some other issue like a misconfiguration in your init.vim or using the wrong neovim version.

The specific error E518 is because vim is trying to set separator style as a native option rather than just for this plugin I don't know why that would be. I suggest very carefully looking over your config and taking things out. There isn't really enough in this issue as is to pinpoint the problem.

**Comment by OldWorldOrdr** [comment]
thanks for the advice

**Comment by akinsho** [comment]
@OldWorldOrdr looking at your `init.vim`

this is erroring because you are doing
`set separator_style`
this is not correct and you should not have this line in your config

**Comment by OldWorldOrdr** [comment]
> @OldWorldOrdr looking at your `init.vim`
> 
> this is erroring because you are doing
> `set separator_style`
> this is not correct and you should not have this line in your config
Ahh I forgot to remove that thanks
