### ISSUE TITLE
[Bug]: The color of the separator is incorrect.

### ISSUE THREAD

**Issue by singlexyz** [akinsho/bufferline.nvim#510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Now Looks like:

<img width="601" alt="图片" src="https://user-images.githubusercontent.com/4456413/184651080-744b5100-cc2c-44e7-a134-274d4190a030.png">

### What did you expect to happen?

Should looks like:

<img width="710" alt="图片" src="https://user-images.githubusercontent.com/4456413/184649942-393f021b-4985-41ea-a1db-7c1515cfde41.png">

### Config

```lua
require("bufferline").setup({
  options = {
    separator_style = "slant",
    diagnostics = "nvim_lsp",
  },
})

vim.keymap.set("n", ")", ":BufferLineCycleNext<cr>", { silent = true })
vim.keymap.set("n", "(", ":BufferLineCyclePrev<cr>", { silent = true })
```

### Additional Information

The color of the separator is incorrect, but as long as enter  `nvim`, the source configuration file will return to normal.

As soon as I switch back to https://github.com/akinsho/bufferline.nvim/commit/2e5d92efacf40d488c4647a9e3e5100357b184cf (v2.5.1), It works fine.

### commit

After 2e5d92efacf40d488c4647a9e3e5100357b184cf

**Comment by akinsho** [comment]
@singlexyz I'm unable to reproduce this. In all likelihood, this relates to your config and how things are being set up, i.e. when the colorscheme is called etc. The config you add will not be enough to reproduce this issue (please do not post your whole config though, as I don't have the time to go through an entire config).

The commit you point out does *nothing to change highlights* it only adds the ability to show duplication prefixes in tabs, so is presumably not even related to your config at all.

In order for this issue to be actionable you need to determine what exact steps I would need to reproduce this exact issue but since I see lots of issue about highlights they almost always come down to some sort of colorscheme timing/loading issue or an error being missed during loading somewhere

**Comment by Durev** [comment]
@akinsho just fyi I noticed the same issue when updating bufferline from commit `2e5d92efacf40d488c4647a9e3e5100357b184cf` to commit `f126f37177cb1902fa785897e038e00f2dca163e`.
Not sure which change between the two triggers the "bug".

I indeed fixed the problem by changing the order in which my plugins and colorscheme are respectively loaded, ie in my `init.vim` going from
```vim
source $HOME/.dotfiles/nvim/config/plugins.vim     " Plugins specific settings (vim script)
source $HOME/.dotfiles/nvim/config/plugins.lua     " Plugins specific settings (lua)
source $HOME/.dotfiles/nvim/config/colorscheme.vim " Colorscheme
```
to
```vim
source $HOME/.dotfiles/nvim/config/colorscheme.vim " Colorscheme
source $HOME/.dotfiles/nvim/config/plugins.vim     " Plugins specific settings (vim script)
source $HOME/.dotfiles/nvim/config/plugins.lua     " Plugins specific settings (lua)
```

The colorscheme I'm using is [material](https://github.com/kaicataldo/material.vim).

I can try to boil down my config so a small one if you want to reproduce the issue.

**Comment by akinsho** [comment]
@Durev I don't know what's in those files, so they're not really a good jumping off point for a reproduction for me. I'd need a minimal example and ideally a single commit that introduces the issue if it is truly an issue. In general, your colorscheme should be loaded before this plugin because when the plugin runs setup it will check colours that exist and use those to create its highlights. In theory, it doesn't matter since whenever a colorscheme is set it should call the `ColorScheme` autocmd which should trigger a re setup of this plugin.

**Comment by Durev** [comment]
@akinsho 
[fd53af1 ](https://github.com/akinsho/bufferline.nvim/commit/fd53af18ac66b799d6edbaa74431a7bc1be832de) fixed the issue on my side.

That was quick!

Thanks 🙏
