### ISSUE TITLE
[Feature Request]: Custom highlight group for filetype icons

### ISSUE THREAD

**Issue by EmDash00** [akinsho/bufferline.nvim#528]
### What?

 My colorscheme doesn't currently support bufferline so I made custom overrides for the highlight groups. I've looked around quite a bit for the filetype icon highlight group but I haven't been able to find one. 

I sincerely apologize I'm just overlooking. If there is one, could someone please point me in the right direction? 

### Why?

Currently have odd coloring of the filetype icon on inactive buffers as shown below.

![Screenshot from 2022-08-25 20-32-25](https://user-images.githubusercontent.com/22357488/186791969-f9c31ff6-bbde-4183-80ae-099c3064c211.png)

Feel like there should be a way to make the icon's background color match the rest of the buffer.

**Comment by akinsho** [comment]
@EmDash00 this plugin is designed not to need specific theming from a colorscheme, it shouldn't really matter if your plugin supports it or not. If you are tweaking the highlights because you'd prefer they were different, then I strongly suggest you do this by using the `config.highlights` table. Trying to manually override the highlights of this plugin outside the highlights table is strongly advised against.

I won't be exposing and maintaining a list of highlights for icons, as this will be very time-consuming for me and shouldn't be needed. These icons are highlighted dynamically the first time a new one is encountered by taking the colour of the background of the parent element it is in. If you are not consistently/correctly changing the highlights of it's parent, then weirdness is bound to happen.

FWIW when opening an issue in the future please include, the version of the plugin you are using i.e. the commit or tag, the configuration required to reproduce what you are describing as well.

**Comment by nullchilly** [comment]
@akinsho I am pretty sure the `BufferLineDevIconSelected` used to match `BufferLineBufferSelected`

Bufferline auto-generated highlight on `Catppuccin latte` isn't exactly as good as [catppuccin/groups/integrations/bufferline.lua](https://github.com/catppuccin/nvim/blob/main/lua/catppuccin/groups/integrations/bufferline.lua)
![image](https://user-images.githubusercontent.com/56817415/186876322-04f59ec0-595b-4a1a-b230-292015ae9663.png)
I would like to follow the guidelines and continue to support bufferline integration. Maybe something like this:

```lua
bufferline.setup{ highlights = require("catppuccin.integrations.bufferline") }
```
However this also means that our ability to change colorscheme on the fly is non-existence, switching from light theme to dark theme bufferline will still keep the same color in highlights table.

My proposal is something like this that reload on ColorScheme autocmd

```lua
bufferline.setup{ highlights = function() return require("catppuccin.integrations.bufferline") end }
```

**Comment by akinsho** [comment]
@nullchilly I don't know exactly what you are getting at. The icon highlights have always been of the format `BufferLineDevIconLua`, BufferLineDevIconLuaSelected`, `BufferLineDevIconLuaInactive` (maybe a word moved, but I don't think so). Each icon highlight takes the highlights already defined by `web-dev-icons` and just adds a variant so that there is a matching background highlight for each buffer state. 

These variants are *still* based on `selected`, `visible` etc. that didn't change. The example you show of passing in a colorscheme specific override is what I had always preferred for colorschemes to do rather than to try and completely override my highlights outside the setup function.

Re. the example you give, you could always just make sure that your integration module returns a function not a table which probably a better way to do this in general, so it's dynamic.

**Comment by nullchilly** [comment]
@akinsho We have `:Catppuccin latte/frappe/macchiato/mocha` to change the colorscheme's flavour on the fly

This means when bufferline.setup is called once the user highlights table is set forever

https://github.com/akinsho/bufferline.nvim/blob/fb7b17362eb6eedc57c37bdfd364f8e7d8149e31/lua/bufferline.lua#L168-L172

What I am asking is to support `self.highlights` as a function and trigger after ColorScheme autocmd

https://github.com/akinsho/bufferline.nvim/blob/fb7b17362eb6eedc57c37bdfd364f8e7d8149e31/lua/bufferline/config.lua#L148

to

```lua
 self.highlights = vim.tbl_deep_extend("force", defaults.highlights, self.user_highlights() or {}) 
```

**Comment by akinsho** [comment]
@nullchilly [*highlights already supports a function*](https://github.com/akinsho/dotfiles/blob/2fe8a7e9b38b46e7e090c68317b4763d073a5515/.config/nvim/lua/as/plugins/bufferline.lua#L13)

**Comment by akinsho** [comment]
I feel that this conversation is distracting from the OP's actual issue, can we please leave off conversations about catpuccin and other things like that to another issue if needed. As far as I can tell, there is no real issue since what you are describing for catpuccin can already be done and does not relate to this issue at all.

**Comment by nullchilly** [comment]
@akinsho Thanks and sorry, feel free to mark comments are off-topic

**Comment by EmDash00** [comment]
>it shouldn't really matter if your plugin supports it or not. If you are tweaking the highlights because you'd prefer they were different, then I strongly suggest you do this by using the config.highlights table. Trying to manually override the highlights of this plugin outside the highlights table is strongly advised against.

Seems like this was the problem. I manually overrode the colorschemes with an au command after the colorscheme is loaded. Below is what I did. I think it must have been something odd about my configuration (not entirely sure what) because using the colorscheme defaults chosen by bufferline.nvim now works. Either way, lesson learned. Thanks for the response. 

lua/colors/init.lua
```lua
colors = {}

local cmd = vim.cmd
local api = vim.api

function colors.set_hls(highlights) 
  for hl, params in pairs(highlights) do 
    local ns_id = 0

    if params.ns_id ~= nil then
      ns_id = params.ns_id
    end

    api.nvim_set_hl(ns_id, hl, params)
  end
end

api.nvim_create_autocmd(
  'ColorScheme', 
  {
    pattern = '*',
    callback = function()
      require('colors.nvim')
      require('colors.lspkinds')
      require('colors.diagnostic')
      --require('colors.bufferline')
      require('colors.nvim_tree')
    end
  }
)
```

lua/colors/bufferline.lua
```lua
local bgcolor_inactive = '#1e2127'
local bgcolor_active = '#282c34'

local highlights = {
  BufferLineFill = {fg='#5c6370', bg='#16181c'},
  
  BufferLineSeparator = {fg='#16181c', bg=bgcolor_inactive},
  BufferLineSeparatorSelected = {fg='#16181c', bg=bgcolor_active},
  BufferLineSeparatorVisible = {fg='#16181c', bg=bgcolor_active},

  BufferLineTab = {fg='#5c6370', bg=bgcolor_inactive},
  BufferLineTabSeparator = {fg='#16181c', bg=bgcolor_inactive},
  BufferLineTabSelected = {fg='#61afef', bg=bgcolor_active},

  --BufferLineBufferVisible = {fg='#80a0ff', bg=bgcolor_active},
  --
  BufferLineNumbers = {fg=bgcolor_inactive},
  BufferLineBackground = {fg='#5c6370', bg=bgcolor_inactive},
  BufferLineDiagnostic = {fg='#454a54', bg=bgcolor_inactive},

  BufferLineDuplicate = {cterm={italic = true}, bg=bgcolor_inactive, italic=true},
  BufferLineError = {fg='#5c6370', bg=bgcolor_inactive, sp='#ff0000'},
  BufferLineWarning = {fg='#5c6370', bg=bgcolor_inactive, sp='#ffa500'},
  BufferLineInfo = {fg='#5c6370', bg=bgcolor_inactive, sp='#add8e6'},
  BufferLineHint = {fg='#5c6370', bg=bgcolor_inactive, sp='#d3d3d3'},


  --BufferLineNumbers = {bg=bgcolor_inactive},
  BufferLineOffsetSeparator = {bg=bgcolor_inactive},
  BufferLineErrorDiagnostic = {fg='#454a54', bg=bgcolor_inactive, sp='#bf0000'},
  BufferLineWarningDiagnostic = {fg='#454a54', bg=bgcolor_inactive, sp='#bf7b00'},
  BufferLineInfoDiagnostic = {fg='#454a54', bg=bgcolor_inactive, sp='#81a2ac'},
  BufferLineHintDiagnostic = {fg='#454a54', bg=bgcolor_inactive, sp='#9e9e9e'},

  BufferLineModified = {fg='#98c379', bg=bgcolor_inactive},
  BufferLineModifiedVisible = {fg='#98c379', bg=bgcolor_active},
  BufferLineModifiedSelected = {fg='#98c379', bg=bgcolor_active},

  BufferLineIndicatorSelected = {fg='#61afef', bg=bgcolor_active},
  BufferLineIndicatorVisible = {fg='#24282f', bg=bgcolor_active},
  BufferLineGroupSeparator = {fg='#5c6370', bg='#16181c'},

  BufferLineBuffer = {fg='#5c6370', bg=bgcolor_inactive},
}

require('colors').set_hls(highlights) -- Loop through the table and set the highlights.
```

**Comment by samEngineering** [comment]
I was having the exact same problem with the icon colors. I set every `BufferLine<...>` highlight group in a similar way but could not get the icons to work right. Now I'm not doing it like that and trying the way suggested in the help page but nothing is changing. I just keep seeing the default settings. @EmDash00, how did you resolve this problem if I may ask?

version:
```
NVIM v0.8.3
```

config:
```
local status, bufferline = pcall(require, "bufferline")
if not status then
   return
end


bufferline.setup({
   options = {
      mode = "tabs",
      numbers = "none",

      close_icon = false,
      left_truc_marker = false,
      right_truc_marker = false,
      modified_icon = "",

      max_name_length = 18,
      max_prefix_length = 15,
      truncate_names = true,
      tab_size = 25,

      diagnostics = false,
      diagnostics_update_in_insert = false,

      color_icons = true,
      show_buffer_icons = true,
      show_buffer_default_icon = false,
      show_buffer_close_icons = false,
      show_close_icon = false,
      show_tab_indicators = false,
      show_duplicate_prefix = true,

      separator_style = "slant",
      enforce_regular_tabs = true,
      always_show_bufferline = true,

      highlights = {
         fill = { fg = Black, bg = Black },
         background = { fg = DarkBlack, bg = DarkBlack },
         tab = { fg=Gray, bg=Black, bold=true, italic=true },
         tab_selected = { fg=Blue, bold=true, italic=true },
         buffer_selected = { fg=Blue, bold=true, italic=true },
         buffer_visible = { fg=Gray, bg=Black, bold=true, italic=true },
         separator = { fg='#ffffff', bg='#ffffff' },
         separator_selected = { fg='#ffffff', bg='#ffffff' },
         separator_visible = { fg='#ffffff', bg='#ffffff' },
      },

      hover = {
          enabled = false,
      },
   }
})
```
