### ISSUE TITLE
How to change underline color?

### ISSUE THREAD

**Issue by babygau** [akinsho/bufferline.nvim#545]
I'd love to change the bufferline underline color, but couldn't find any relevant highlight group 
<img width="309" alt="Screen Shot 2022-09-12 at 7 51 27 pm" src="https://user-images.githubusercontent.com/1514823/189624774-d6a39be1-1028-4eb6-b7da-32b81838dcd8.png">
Thank you!

**Comment by akinsho** [comment]
@babygau the underline is the `indicator` so you should use the highlights for `indicator_selected`

**Comment by akinsho** [comment]
@babygau underline highlights are controlled by the `special` key in neovim. If you want to change the colour of and underlines you should set special

**Comment by akinsho** [comment]
@babygau sorry the highlight should actually be 
```lua
buffer_selected = { sp = 'blah', ... -- other attributes }
```

**Comment by akinsho** [comment]
@babygau bufferline will check the value of `TabLineSel` background first then foreground and use those colours for the indicator selected, I don't know why it wouldn't work for you since I don't know how you set your highlights at all or what your config looks like. Tbh I'd rather not go down that rabbit hole of debugging it and will leave that to you. If using `buffer_selected` works, then you can just use that.

**Comment by Alex-vZyl** [comment]
@babygau Would you mind just putting the config you used here for completeness?
