### ISSUE TITLE
Slant separator is ugly on transparent fill background

### ISSUE THREAD

**Issue by latipun7** [akinsho/bufferline.nvim#547]
Currently slant (and padded_slant) is not suitable when configuring fill bg to transparent (`NONE`).
```lua
highlights = {
  fill = { bg = "NONE" }
}
```
![image](https://user-images.githubusercontent.com/20012970/190068648-bff19e45-1244-4f8d-aeb7-1d4c84025405.png)

With that, I still can't change separator bg to NONE because it uses "" and "", so for example on the image above, that black is foreground of slant separator chars. I don't think I can make transparent foreground, because when I try to change `separator = { fg = "NONE" }` it would change to white instead of transparent foreground.
https://github.com/akinsho/bufferline.nvim/blob/ffa1d0009f5e52d3d32d08c9a781f18b2b2ef507/lua/bufferline/constants.lua#L20

```lua
highlights = {
  fill = { bg = "NONE" },
  separator = { fg = "NONE" },
  separator_selected = { fg = "NONE" },
}
```
![image](https://user-images.githubusercontent.com/20012970/190076808-0c991462-967d-47dc-91a7-cae54d58ed46.png)

Please change slant chars to "" (`\u{e0b8}`) and "" (`\u{e0ba}`) and adapt the foreground to the correct highlight, so the background can be set to `NONE` (transparent).

Thank you 🙏

**Comment by akinsho** [comment]
@latipun7 this plugin was not designed with transparent usage in mind, using this plugin with the slant style and transparency makes even less sense to me, but users are free to do as they please ofc 🤷🏿‍♂️. I chose the current slant characters on purpose because that was what worked with the implementation. I won't be doing a big refactor to accommodate this fairly niche usage of this plugin.

You as a user can change the separator characters yourself using the `separator_style` option. Regarding making the colours transparent, that exercise is entirely up to you. I have never used transparency with neovim so have no idea how to achieve it. Other users have, though, so maybe look for similar issues or at other people's dotfiles

**Comment by mariospicross** [comment]
did you find a good way around this?

**Comment by latipun7** [comment]
@mariospicross no, I just disable transparency only on bufferline.
![](https://user-images.githubusercontent.com/20012970/211981618-633f41a0-8962-4988-89b4-73f6942271cd.png)

**Comment by idr4n** [comment]
> no, I just disable transparency on bufferline. I think it's still nice ✨ 

@latipun7 How did you disable transparency on bufferline only. Is that a setting in catpuccin? Thanks in advance!

**Comment by latipun7** [comment]
> How did you disable transparency on bufferline only. Is that a setting in catpuccin? Thanks in advance!

Yes, it's from the bufferline integration setting on catppuccin (https://github.com/latipun7/dotfiles/blob/fdfb04acb1fdce281a917c4c9924248b09ff0024/home/dot_config/exact_nvim/exact_lua/exact_plugins/bufferline.lua#L17-L32).
