### ISSUE TITLE
[Feature Request]: offset highlights accept color specification like buffers

### ISSUE THREAD

**Issue by tobealive** [akinsho/bufferline.nvim#553]
### What?

It would be nice to be able to use a table like with `nvim_set_hl` in the offset highlight setting. 

Maybe even move the highlight key out of the offset and add a `offset` group to the rest of the bufferline highlights.

### Why?

Currently(as far as I can see), for using a custom highlight in the offset I need to create a highlight group and specify this highlight group as value.

Being able to define a highlight value like in the rest of the plugin would be a nice extension and would improve consistency.

**Comment by akinsho** [comment]
Whilst it might seem like better consistency as far as the actual codebase is concerned, I don't think this would make anything more consistent.

Adding an `offset` group will immediately result in a request for a left and right one and tbh is actually less flexible because for example I use different highlights for different offsets. I darken some sidebars and want those to have different offset colours, whereas I don't darken others, so they can't/shouldn't/won't share the same highlight.

Tbh this seems like it will reduce flexibility and add more code to maintain for this plugin and the only upside would be that I do the `nvim_set_hl` call for the user instead 🤷🏿. The main reason I went with a highlight group was the original use case that resulted in all these offsets was to show nvim-tree as full height, so it made the most sense to link the highlight of the offset directly to `NvimTreeNormal`. This is still largely the case.

**Comment by tobealive** [comment]
Thanks for shedding some light and some of your stardust. Its always great to get some insight.

**Comment by akinsho** [comment]
Gonna (presumptuously) close this out as resolved
