### ISSUE TITLE
[Bug]: separator_style = { 'any', 'any' } has no effect

### ISSUE THREAD

**Issue by Diaoul** [akinsho/bufferline.nvim#555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Docs says
```
-- can also be a table containing 2 custom separators
-- [focused and unfocused]. eg: { '|', '|' }
separator_style = "slant" | "thick" | "thin" | { 'any', 'any' },
```

However setting
```
separator_style = { "|", "|" },
```
Does not work

### What did you expect to happen?

It works

### Config

```
separator_style = { "|", "|" },
```

### Additional Information

...

**Comment by akinsho** [comment]
@Diaoul I've just tested this locally and verified that it works. You are in all likelihood not configuring this properly. All options should be inside the options table, i.e.
```lua
bufferline.setup({ options = { separator_style = {...} }})
```
Please read through the provided configuration example *carefully*

**Comment by Diaoul** [comment]
I've been swapping between "slant" and this so my config is alright, here is the full one:

```
require("bufferline").setup {
    options = {
        color_icons = false,
        show_buffer_close_icons = false,
        show_close_icon = false,
        separator_style = { "", "" },
    },
}

```

**Comment by Diaoul** [comment]
plugins.lua

```
use {
    "akinsho/bufferline.nvim",
    tag = "v2.*",
    config = function()
        require("diaoul.bufferline").config()
    end,
}
```

**Comment by akinsho** [comment]
@Diaoul setting that value results in 

<img width="624" alt="image" src="https://user-images.githubusercontent.com/22454918/190863239-f05fff45-5d1b-417b-b724-dd0a46f0eeca.png">

For me, as a general rule, I don't debug individual user configs since this is very time-consuming for me across multiple plugins. I don't know how your config is set up and if you are making sure things are correctly reloaded etc. My main priority is to ensure the plugin is not broken, which appears not to be the case.

**Comment by Diaoul** [comment]
Well, looks like it's working for you at least :laughing: 
I'll investigate what is wrong on my side, maybe some incompatibility somewhere :thinking: 

Thanks for taking the time to check :pray:

**Comment by Diaoul** [comment]
I've tried other separators and no effect either :shrug: 
```
separator_style = { "", "" },
```

**Comment by Diaoul** [comment]
Turns out loading bufferline before other plugins seems to fix the issue (but breaks other things...) :tada:

**Comment by Diaoul** [comment]
I was wrong, it works in any order actually.

I just missed it because it did not behave as I expected it to. I compared the behavior of my config with the `slant` one but it turns out the slant config is _special_: it has leading and ending separators.

With those highlights for better visibility:
```
separator = {
    fg = palette.bright_aqua,
    bg = palette.faded_aqua,
},
separator_selected = {
    fg = palette.bright_red,
    bg = palette.faded_red,
},
separator_visible = {
    fg = palette.bright_green,
    bg = palette.faded_green,
},
```
Here is the "normal" separator behavior (`thin` in this case):
![image](https://user-images.githubusercontent.com/319220/190864901-4d9985ba-8a3e-428a-84aa-a210d9ec11a3.png)

And the `slant` one with leading and ending separators:
![image](https://user-images.githubusercontent.com/319220/190864938-eae340d8-ce42-4faf-bafa-a1b28c70b431.png)

@akinsho should I open a feature request to have configurable leading and ending separators or is that something you won't consider?

**Comment by akinsho** [comment]
@Diaoul tbh people request functionality like this quite often wanting to change the separators. To be honest, I'm not particularly interested in implementing this. I have a plan to potentially make each tab more configurable, but ultimately the reason I created this plugin was to emulate the style of GUI editors like VSCode, Atom or sublime. I personally feel like the existing styles cover that so I'm not very much inclined to spend time allowing all the custom variations that people want. If you are willing to open a PR to do it yourself. Then I would review that PR if it was well implemented otherwise, I think I'm not going to do this. It might come out as part of my plan for more customization in the future if I follow through with it, but it might not.

**Comment by Diaoul** [comment]
Very clear thanks. I'll bufferline a bit and eventually submit a PR for that.
