### ISSUE TITLE
[Bug]: Configured nvim-web-devicons overrides are ignored

### ISSUE THREAD

**Issue by sindrets** [akinsho/bufferline.nvim#568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After a recent commit (d545bf8493c26aca0aeeddfd38795f3b4a98b90f) my configured icon overrides are no longer respected. Not sure whether it's nvim-web-devicons or bufferline that's at fault here, but it's worth noting that it *only* seems to happen when devicons is configured with the option `default = true` (see attached minimal config).

### What did you expect to happen?

Bufferline.nvim uses the icons I've configured through nvim-web-devicons.

### Config

<details>
  <summary><b>Minimal config for reproduction:</b></summary>

```lua
-- Usage: `nvim --clean -u mini.lua`
vim.g.loaded_remote_plugins = 1
vim.opt.runtimepath = "$VIMRUNTIME"
vim.opt.packpath = "/tmp/nvim/site"
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      {
        "kyazdani42/nvim-web-devicons",
        config = function()
          require("nvim-web-devicons").setup({
            override = {
              bar = {
                icon = "#",
                color = "#e37933",
                name = "Bar",
              },
            },
            default = true,
          })
        end,
      },
      {
        "akinsho/bufferline.nvim",
        -- commit = "d545bf8493c26aca0aeeddfd38795f3b4a98b90f^",
        after = "nvim-web-devicons",
        config = function()
          require('bufferline').setup({})
        end,
      },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  })
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing dependencies...")
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end

vim.opt.termguicolors = true

load_plugins()
require("packer").sync()

_G.load_config = function()
  vim.cmd("f foo.bar")
end
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

</details>

### Additional Information

...

### commit

d545bf8493c26aca0aeeddfd38795f3b4a98b90f

**Comment by HumblePresent** [comment]
I've also been experiencing this issue. For me it's not that my `nvim-web-devicons` overrides aren't respected, but the correct icon only shows once the buffer becomes active. Before that my default icon set in `nvim-web-devicons` is used.

#### Here are the results of my investigation:
1. Setting `default = true` in the `nvim-web-devicons` config will override the `default` option passed to functions like `get_icon_by_filetype()` and `get_icon()` so I believe the following section that was added in commit d545bf8 does not work exactly as intented **IF** `default = true` in the `nvim-web-devicons` config.
https://github.com/akinsho/bufferline.nvim/blob/83bf4dc7bff642e145c8b4547aa596803a8b4dc4/lua/bufferline/utils/init.lua#L189-L193
2. After some light debugging it looks like `require("bufferline.utils").get_icon()` is called with `opts.filetype` set as an empty string **NOT** `nil` for buffers that have not yet been active. This causes `opts.filetype` to be truthy and `webdev_icons.get_icon_by_filetype()` to be called which returns a default icon if the issue described above is also at play. This explaines the behavior I am experiencing where all buffers but the active one have the default icon.

#### Possible solution:
After chaning this line 
https://github.com/akinsho/bufferline.nvim/blob/83bf4dc7bff642e145c8b4547aa596803a8b4dc4/lua/bufferline/utils/init.lua#L190
to `if M.is_truthy(opts.filetype) then` I no longer see the issue because the empty string for `opts.filetype` is detected as falsy. I have not dug deeper to determine why the `filetype` is not set for buffers that have not yet been active, but it appears to be upstream behavior in neovim itself. I can submit a PR with this change if this also fixes the issue for @sindrets.

**Comment by HumblePresent** [comment]
I just noticed that my proposed solution still does not address issue 1. Maybe it's best to revert the change to this code in d545bf8 and only lookup icons by name and extension?

**Comment by akinsho** [comment]
@HumblePresent whilst this would fix your issue, it would bring the author of the issue that led to that commit in the first place coming back to me to complain that their filetype icons no longer appear as they expected

Regarding overrides not working I believe it is an outstanding issue that they haven't been working for a long time see #191.

Regarding setting default to true or not, this is controllable by the user's config as the value there is a `config.options.show_buffer_default_icon`

**Comment by akinsho** [comment]
If an empty filetype comes back as `""` rather than `nil` that is worth fixing regardless, I'd say.

**Comment by sindrets** [comment]
> Regarding overrides not working I believe it is an outstanding issue that they haven't been working for a long time

@akinsho Yes, they were working up until just before that commit, as can be demonstrated by uncommenting the line in the minimal config pinning bufferline to the commit prior to d545bf8493c26aca0aeeddfd38795f3b4a98b90f.

But the actual issue seems to be that nvim-web-devicons does not respect the options passed to its `get_icon*` API:

https://github.com/kyazdani42/nvim-web-devicons/blob/969728506c0175644a1d448f55e311ccdada7eaf/lua/nvim-web-devicons.lua#L1642

If `global_opts.default` is `true`, then `has_default` will always evaluate to `true` regardless of what options were passed to the function. Someone has already [opened a PR to fix it though](https://github.com/kyazdani42/nvim-web-devicons/pull/158).

> Regarding setting default to true or not, this is controllable by the user's config as the value there is a `config.options.show_buffer_default_icon`

That's only a partial solution for bufferline specifically. I want nvim-web-devicons to *always* provide default icons to all plugins that depend on it, not just bufferline.

I'll close this, as the actual issue lies with nvim-web-devicons.
