### ISSUE TITLE
[Bug]: Wrong separator for tabs

### ISSUE THREAD

**Issue by Nik-i-Net** [akinsho/bufferline.nvim#569]
### What happened?

When using "mode = buffers", tab sepatators are wrong.

### What did you expect to happen?

Correct separators or the ability to put a standard separator for tabs.

### Config

![Screenshot from 2022-09-26 14-22-12](https://user-images.githubusercontent.com/91474300/192265587-90e6f36a-102f-4a50-a12c-4b8855533e7f.png)

### Additional Information

This behavior on any color scheme.

**Comment by akinsho** [comment]
@Nik-i-Net this issue is invalid as there is no relationship between separator style and mode. You have set the separator style to slant, and it appears as slant which is what it is supposed to do. If you still believe something is wrong please clarify *very clearly what* and provide a *minimal init.lua* (not a screenshot) that I can use to reproduce any issue

**Comment by Luis-Licea** [comment]
I am having the same issue. The slanted characters are supposed to occur on both sides of the tab, but only occur on one. This does not depend on the color scheme, as Nik mentioned. Here are some examples.
![image](https://user-images.githubusercontent.com/48164786/194729826-25ab9f04-71db-4f45-baec-423febf21661.png)
![image](https://user-images.githubusercontent.com/48164786/194729917-cfcb6bd3-3f8c-4a46-8ec9-654f8ea452d2.png)

**Comment by akinsho** [comment]
@Luis-Licea the minimal tab indicators aren't configurable with custom separators, they aren't expected to have slanted sides at all, I'm not really sure how you're achieving that image in the screenshot but it definitely isn't a supported feature so I'd say this isn't a bug since I never built it to do what you're trying to do. Only the actual full buffer tabs can have custom separators

**Comment by knmac** [comment]
I think the problem here is that the "tab tabs" are rendered with only one separator. This is seen in the function ` render(tabpage, is_active, style, highlights)` in the file `tabpages.lua`:

Original code:
```lua
local function render(tabpage, is_active, style, highlights)
  local h = highlights
  local hl = is_active and h.tab_selected.hl_group or h.tab.hl_group
  local separator_hl = is_active and h.tab_separator_selected.hl_group or h.tab_separator.hl_group
  local chars = constants.sep_chars[style] or constants.sep_chars.thin
  local separator_component = chars[2]
  local name = padding .. padding .. tabpage.tabnr .. padding
  return {
    { highlight = hl, text = name, attr = { prefix = tab_click_component(tabpage.tabnr) } },
    { highlight = separator_hl, text = separator_component },
  }
end
```

We can see that the `separator_component` only uses the 2nd character from `constants.sep_chars[style]` (here, `style` is slant). So, an easy fix for this is
```lua
local function render(tabpage, is_active, style, highlights)
  local h = highlights
  local hl = is_active and h.tab_selected.hl_group or h.tab.hl_group
  local separator_hl = is_active and h.tab_separator_selected.hl_group or h.tab_separator.hl_group
  local chars = constants.sep_chars[style] or constants.sep_chars.thin
  local name = padding .. tabpage.tabnr .. padding
  return {
    { highlight = separator_hl, text = chars[2] },
    { highlight = hl, text = name, attr = { prefix = tab_click_component(tabpage.tabnr) } },
    { highlight = separator_hl, text = chars[1] },
  }
end
```

Here, I also remove the extra left padding from the `name` variable to center the text. For some reasons, I also needs to swap the left and right separators in the return line to make it to be "in-oder".

**Comment by akinsho** [comment]
I haven't seen this issue myself, but if this change fixes the issue for people experiencing it I'm happy to review a PR when I get some time
