### ISSUE TITLE
Should offsets filetype accept table or string or regular expression?

### ISSUE THREAD

**Issue by emxxjnm** [akinsho/bufferline.nvim#585]
![image](https://user-images.githubusercontent.com/54089360/195260536-51e75223-d50f-46e9-933f-2f2634c765fa.png)

Should offsets filetype accept table or string or regular expression?

for example: [dap-ui](https://github.com/rcarriga/nvim-dap-ui#configuration) 

its layout is dependent on the order of elements in the configuration, the filetype of each element panel is something like dapui_\<element\>

![image](https://user-images.githubusercontent.com/54089360/195261904-105854e0-435b-4500-910d-c5ef3d2eb4bf.png)

**Comment by akinsho** [comment]
The offsets file type expects a string which maps directly to a file type. It is not a pattern or regular expression

**Comment by akinsho** [comment]
Since this seems like a question, and it's been answered above, I will close this out. If you think it should word as a pattern, please feel free to submit a PR. Currently, this will require a new field since users will expect it to take a literal string, so if it now takes a pattern that should be a new field.
