### ISSUE TITLE
[Question]: Don't show "[No Name]" tab

### ISSUE THREAD

**Issue by yannjor** [akinsho/bufferline.nvim#610]
Is it possible to filter out the "[No Name]" tab that is visible on startup somehow? I tried with

```lua
custom_filter = function(buf, buf_nums)
    return vim.fn.bufname(buf) == ""
end,
```
and 
```lua
custom_filter = function(buf, buf_nums)
    return vim.fn.bufname(buf) == "[No Name]"
end,
```
but no success.

Thanks in advance!

**Comment by akinsho** [comment]
@yannjor this buffer is created by neovim if you want to hide any buffer without a name (which I really do not recommend) you can try
```lua
custom_filter = function(buf, buf_nums)
    return vim.fn.bufname(buf) == ""
end,
```

**Comment by yannjor** [comment]
Hi @akinsho  this is indeed what I tried but it doesn't work. Why do you recommend against this?

**Comment by akinsho** [comment]
@yannjor those are buffers that actually exist in neovim either a plugin is making them by mistake or sometimes when you open neovim without a session it creates them. It's a bit like opening Microsoft Word with an untitled document, vim might later ask you if you want to save the document, but you won't know what it's talking about. Or tbh a bug could be introduced into a plugin, and it starts making a bunch of empty buffers, and you never even notice since you've hidden them. 🤷🏿 up to you, anyway. As to it not working I'd recommend fiddling a bit and seeing if you can get anything working, if not then I would take a PR to fix it but won't put any work into it myself as I don't believe these should be hidden anyway

**Comment by wardw** [comment]
To filter out unnamed buffers, it's
```lua
custom_filter = function(buf, buf_nums)
    return vim.fn.bufname(buf) ~= ""
end,
```

Only by observation, but it appears that to return `true` is to _keep_ that buffer, not filter it out.
