### ISSUE TITLE
[Feature Request]: Option to toggle showing bufferline, and option to show and then collapse when buffer is changed.

### ISSUE THREAD

**Issue by jam1015** [akinsho/bufferline.nvim#651]
### What?

Two similar features desired.

1:  function to easily toggle whether bufferline is visible. Something where I could make a mapping:

`nnoremap <leader>bt :bufferline_toggle()<CR>`
 
or with a plug mapping

`nmap <leader>bt <Plug>bufferline_toggle`

2: function to show buffer line, from hidden state and close it automatically when buffer changes, or if called when bufferline is already shown, hide bufferline on next buffer change

could make a mapping like

`nmap <leader>bh <Plug>bufferline_change_hide`

### Why?

would be nice to toggle when it is visible and when it is not, and possibly on buffer change.

**Comment by akinsho** [comment]
You can control the visibility of bufferline using the `showtabline` option in neovim natively. That should be enough to work out something like what you want in your own config. I don't think that logic should live here as it's quite specific to your preferences. There is a bug relating to some of the `showtabline` behaviour but I don't know if it will affect you but if it does please post on that issue. Otherwise I'll close this specific one out as this can be solved through using `showtabline` with some lua function to trigger in your specific scenario
