### ISSUE TITLE
[Bug]: Not sure this is a bug, but diagnostic highlight is not set after switching buffers

### ISSUE THREAD

**Issue by steakhutzeee** [akinsho/bufferline.nvim#654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Switching to another buffer does not keep the diagnostic color for the others buffer names.

Also, there is a way to disable the selected buffer tab name to be italic?

### What did you expect to happen?

Buffers to keep their tab name colored also after switching to another buffer.

### Config

```
require("bufferline").setup({
  options = {
    show_close_icon = false,
	show_buffer_close_icons = false,
	diagnostics = "nvim_lsp",
	diagnostics_indicator = nil,
    offsets = {
      {
        filetype = "NvimTree",
        text = "File Explorer",
        text_align = "center",
        separator = true,
      }
    }
  }
})
```

### Additional Information

...

**Comment by akinsho** [comment]
Only just got round to this.

1. It's not an error that inactive buffer's don't have colourful diagnostic colors. This is to avoid things being too noisy visually, not completely for or against but it's currently by design.
2. You can make things not italic or not bold by finding the highlight group that needs changing in the docs and then enabling or disable the feature you want, see `:h bufferline-highlights`
