### ISSUE TITLE
Question: Is there away to get the selected buffer via lua api?

### ISSUE THREAD

**Issue by nerdo** [akinsho/bufferline.nvim#663]
### What?

Expose the selected buffer via lua api (a function call).

### Why?

I have a use case where I want to leverage bufferline to find out the selected buffer so that I can switch to it when another, specialized buffer closes.

`bp` doesn't always give the intended result due to how some of the plugins in my set up work, so I'd really like to just query bufferline for the selected buffer and explicitly go to it.

I see that there is a `get_elements` function, but there doesn't seem to be any information about which buffer is selected.

Is there a way to get that information or would this require adding code to bufferline to expose the selected buffer somehow?

**Comment by akinsho** [comment]
@nerdo I'm not sure why you wouldn't just use native built-in functions to get the current buffer. That can't be different between neovim and bufferline i.e. if bufferline says a buffer is selected it must also be selected in neovim i.e. I recommend just using `vim.api.nvim_get_current_buf()`

**Comment by akinsho** [comment]
@nerdo I think maybe there's some mixture of concepts a little, so it's not a 100% clear what you want. Essentially bufferline only deals with buffers and all the windows contain buffers (unless you are using vim tabs, then for the sake of this conversation there are no tabs of any kind). Bufferline ignore certain buffers if they are `&nobuflisted` i.e. they have been designed not to show up in the buffer list which most plugins do.

Re. this selected buffer state you are alluding to what I'm trying to communicate is that bufferline does not carry special state for this really, it just directly reproduces what neovim has in state so checking what bufferline is doing isn't needed you can just check what neovim has as values. If a floating window is opened, that window's buffer is the current buffer, there is no other current buffer. Bufferline does not keep reference to the previous buffer. Vim does using `:h alternate-file`, bufferline also will highlight *visible buffers* so if a buffer is still on-screen but not focused it should show with a different highlight.

Anyway, the TLDR is the special state you are looking to use doesn't actually exist as a stored field in bufferline because it doesn't need to.

**Comment by nerdo** [comment]
Thanks for taking the time to respond and explain. I think you revealed what I was after and didn't fully understand until now.

That is the `&nobuflisted` attribute (property? behavior?). I think I just need to track the last buffer that does not have that attribute. That should be pretty simple to do with an `autocmd`. I just didn't realize how bufferline was doing what it does so I was looking to leverage it instead of re-inventing the wheel, but it seems pretty straightforward now.

P.S. I wasn't sure what else to call the tab-like UI elements other than "tab"s - that is what I meant by that.
