### ISSUE TITLE
[Feature Request]:  Keep pin order os the buffers

### ISSUE THREAD

**Issue by otavioschwanck** [akinsho/bufferline.nvim#685]
### What?

When i pin some buffer, it not always go to the end os pin list (pin list is ordered by bufid).  The natural way should be always go to the final of the pin list.

### Why?

The current behaviour is not natural and keep messing the order.

**Comment by otavioschwanck** [comment]
@akinsho i want to implement this.  Any help where to implement this on the code?

**Comment by akinsho** [comment]
This will be fairly difficult probably because it will mean having to re-sort the pinned buffers whenever a new pinned buffer is added/ensuring that no other sorting command causes them to loose their order. Natural feeling or not this maybe a bit tough. let me have a think of a solution. It might need to big a code change for too small a value which won't be acceptable
