### ISSUE TITLE
[Feature Request]: Prevent bufferline from wrapping over (cycling) to the opposite edge of the bufferlist?

### ISSUE THREAD

**Issue by kohane27** [akinsho/bufferline.nvim#700]
### What?

Hello there. Hope you're doing well. Thank you for creating `bufferline.nvim`.

## Scenario

1. Current buffer (end of bufferlist):
![2023-03-03-11-16-53](https://user-images.githubusercontent.com/57322459/222623496-3a841a64-216d-4c1a-8868-e63cf8a1c12c.png)
2. `:lua BufferLineCycleNext<CR>`
3. Switched to first buffer (first of bufferlist):
![2023-03-03-11-17-11](https://user-images.githubusercontent.com/57322459/222623500-a6ea034b-dc84-4a46-8c6d-1bb96a29e277.png)

## How to prevent this cycling buffer behavior?

When the current buffer is at the end of the bufferlist, when I do `:lua BufferLineCycleNext<CR>`, I want nothing to happen. I don't want this wrap over behavior. I want the focused buffer to retain focus, because there are no next buffer in the direction.

Any input is much appreciated. Thank you:)

**Comment by akinsho** [comment]
This is definitely achievable potentially with a flag in command like `CycleNext stopEnd=true` or something and then skip the logic inside the function that causes it to loop and just do nothing. All this being said I personally have absolutely no need for this feature and so no particular desire to work on it. It's not a complex problem so you could tackle this if it's something you want badly enough @kohane27.

Let me know if you plan to, otherwise I'll close this out in about a week since otherwise issues like this tend to sit open for months/years

**Comment by kohane27** [comment]
Hello @akinsho

Thank you for getting back to me and provider the pointer. I'd create a PR if I do tackle this problem. Thank you again:)
