### ISSUE TITLE
[Bug]: Error on set ctermfg when 'color_icons=false'

### ISSUE THREAD

**Issue by jonathanforhan** [akinsho/bufferline.nvim#702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

reading the docs i set 'color_icons=false', the icons changed accordingly, however there was an error message on startup reading:
![Screenshot from 2023-03-05 19-29-15](https://user-images.githubusercontent.com/99012095/222995673-8eaa8fda-d54f-4c6f-b096-76744cdcb0cd.png)

I looked into the code and changed this:
![Screenshot from 2023-03-05 19-28-35](https://user-images.githubusercontent.com/99012095/222995721-d6e613ec-7d11-4f31-b0cd-a4f998d48c0a.png)

in the 'highlights.lua file':
![Screenshot from 2023-03-05 19-28-45](https://user-images.githubusercontent.com/99012095/222995752-a5c76416-d5c4-458c-ab14-cd258449caef.png)

I don't know the code well enough to know if this is breaking for other aspects but my setup looks fine now with no errors.

The error seemed to be that color was equal to 'fg' and then ctermfg would not accept that as a valid color obviously.

### What did you expect to happen?

No errors on startup

### Config

- tmux
- lazy.nvim package manager
- Linux mint 21
- Gnome terminal

![Screenshot from 2023-03-05 19-31-59](https://user-images.githubusercontent.com/99012095/222995789-61c339dc-0b66-46e8-8d3d-1e62a302f5e1.png)

### Additional Information

...

**Comment by akinsho** [comment]
@jonathanforhan this issue *might be* because you are using a transparent background which unfortunately has proven to be quite a frustrating edge case for this plugin for me. In this case `fg` which is normally a valid value for setting the `fg` of a color to the default `fg` color I think doesn't work with transparent backgrounds, although the issue is usually with `bg` can you try using a solid background and seeing if this is still an issue.
