### ISSUE TITLE
Open new buffer using telescope by replacing current

### ISSUE THREAD

**Issue by xbladesub** [akinsho/bufferline.nvim#704]
Is it possible to configure bufferline so it would replace current buffer with new one if I open a buffer through telescope's `find_files` picker? For example I have 2 buffers in 2 vert splits and I don't want to keep old buffer when I'm opening new one in current split.

Another small question - how can I hide bufferline row without disabling/removing plugin? I want to be able to use Bufferline commands, but in the same time I want to try to disable bufferline row

**Comment by akinsho** [comment]
Hi @xbladesub,

configuring telescope and it's pickers is kind of out of scope for this plugin tbh, it sounds like you want to replace 2 open windows with just one window with the new buffer. I'm sure you can setup some custom action to close other windows and open in the new one. I don't have a solution off the top of my head but maybe ask on telescope's repo or reddit. In general how windows are laid out and really how you open them or not isn't really something bufferline is really directly involved with. It doesn't do any window management on purpose.

Re. the second question you can use the `showtabline` option (`:help showtabline`), FWIW many of bufferline's commands won't make sense if you can't see the bufferline and tbh I won't necessarily address those since they're designed to be used together.
