### ISSUE TITLE
[Bug]: sort_by = 'insert_after_current' stops working after calling :BufferLineMoveNext

### ISSUE THREAD

**Issue by durka** [akinsho/bufferline.nvim#706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After using :BufferLineMoveNext or :BufferLineMovePrev, new buffers always show up at the end of the bufferline.

### What did you expect to happen?

I thought that new buffers would continue to open just to the right of the current one.

### Config

```
            require("bufferline").setup {
                options = {
                    right_mouse_command = '',
                    middle_mouse_command = 'bdelete! %d',
                    separator_style = 'slant',
                    sort_by = 'insert_after_current',
                    hover = {
                        enabled = true,
                        delay = 5,
                        reveal = {'close'}
                    },
                }
            }
```

### Additional Information

nvim v0.8.3

**Comment by akinsho** [comment]
@durka this is not a bug but by design, if you move the buffers yourself you are essentially taking control of the sorting of the bufferline. So bufferline stops using its mechanism and differs to you because maintaining its sort order as well as yours is complicated and messy. I don't intend to change this but PRs welcome if you know how

**Comment by durka** [comment]
Oh okay thanks for the clarification, I didn't realize it was by design.
