### ISSUE TITLE
[Bug]: Artifacts in group name graphic

### ISSUE THREAD

**Issue by rickyelopez** [akinsho/bufferline.nvim#717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I get these little artifacts in my group names:
![image](https://user-images.githubusercontent.com/31072564/228028430-f5a8b81d-5960-4f90-b666-f388dae36e4f.png)
and I can't figure out where they're coming from. I'm probably doing something wrong, but I can't figure out what.

### What did you expect to happen?

I expected there to not be artifacts

### Config

```lua
require("bufferline").setup({
    options = {
        close_command = M.close,
        right_mouse_command = M.close,
        left_mouse_command = "buffer %d",
        middle_mouse_command = nil,
        max_name_length = 18,
        max_prefix_length = 15,
        tab_size = 5,
        diagnostics = "nvim_lsp",
        diagnostics_update_in_insert = false,
        diagnostics_indicator = function(count, level, diagnostics_dict, context)
            return "(" .. count .. ")"
        end,
        show_buffer_icons = true,
        show_buffer_close_icons = false,
        show_close_icon = false,
        show_tab_indicators = false,
        persist_buffer_sort = true,
        enforce_regular_tabs = false,
        sort_by = "relative_directory",
        separator_style = "slant",
        groups = {
            options = {
                toggle_hidden_on_enter = true,
            },
            items = {
                {
                    name = "Configs",
                    highlight = { foreground = "purple" },
                    priority = 1,
                    matcher = function(buf)
                        return buf.path:match("dotfiles") or buf.path:match("%.config")
                    end,
                },
...
```

### Additional Information

I'm using BlexMono patched nerd font with a base16 color scheme, and the tokyonight theme in neovim. I'm not finding any issues with any of those things, and this is the only plugin that is currently giving me artifacts like this.

### commit

3677aceb9a726

**Comment by akinsho** [comment]
@rickyelopez these sort of rendering issue are due to how your terminal emulator and font and showing these symbols. This is out of my hands since I can't really control this behaviour and it's kind of up to each user to figure out what emulator and what fonts work for them.

**Comment by rickyelopez** [comment]
I'm mostly looking for suggestions on how to debug this, do you have any?

**Comment by akinsho** [comment]
@rickyelopez I've used the same terminal emulator for years now so haven't had any issues like this since I don't move between terminals. I'd say try another one and see if it's a terminal emulator issue. If it's the same across emulators then maybe try and see if it's caused by the font. There are lots of posts by (neo)vim users about nerdfonts and glyph rendering problems so there's also probably some stuff around that might help

**Comment by rickyelopez** [comment]
Looks like this is actually just the way these glyphs look with this font.
![image](https://user-images.githubusercontent.com/31072564/228660922-9740aa27-7dfe-4b8d-bcca-327fcf67ed4b.png)

**Comment by akinsho** [comment]
@rickyelopez this isn't actually the case, each string is prefixed with highlight value so they aren't going to necessarily look like they do as raw strings in the code base. I thought the issue you were referring to was the fact that some of your block characters are the wrong height. If your issue is the color of the special characters, this is universally an issue with the users colorscheme and the highlights they've chosen. I've helped debug this sort of issue innumerable times and it's usually a user configuration issue. I'd start with there but this isn't a bug with the plugin itself since it's usually resolved when the user tweaks their highlights. I'm only focusing on *bugs* and when very very good *feature requests* so this will be up to you to figure out.

**Comment by rickyelopez** [comment]
yeah it's all good, I'm working on fixing by specifying the highlights. Thanks
