### ISSUE TITLE
[Bug]: show_buffer_default_icon is deprecated, use get_element_icon = function(buf) return require('nvim-web-devicons').get_ icon(..., {default = false}) instead. See :h deprecated stack traceback:         ...nvim/site/lazy/bufferline.nvim/lua/bufferline/config.lua:65: in function <...nvim/site/lazy/bufferline.nvi m/lua/bufferline/config.lua:65>

### ISSUE THREAD

**Issue by Jasonvim** [akinsho/bufferline.nvim#735]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

when I enter a file, it will be an issue:show_buffer_default_icon is deprecated, use get_element_icon = function(buf) return require('nvim-web-devicons').get_
icon(..., {default = false}) instead. See :h deprecated
stack traceback:
        ...nvim/site/lazy/bufferline.nvim/lua/bufferline/config.lua:65: in function <...nvim/site/lazy/bufferline.nvi
m/lua/bufferline/config.lua:65>

### What did you expect to happen?

Expected behaviour

### Config

Neovim 0.8.3
Ubuntu 22.04(wsl)

### Additional Information

...

**Comment by Jasonvim** [comment]
I used Lazy.nvim to install it.

**Comment by dc3671** [comment]
This is caused by 6ccdee8e931503699eb8f92c7faafd0ad1a8cf69, and you can manually checkout to old version, like 9abbcedd5164d8fead4e2f7a39ed00f5e5e759f2.

**Comment by akinsho** [comment]
@Jasonvim I've deprecated a field `show_buffer_default_icon` in the config, just remove the field if you are not using it. You don't need to go back to previous commits or anything since that won't actually resolve the issue. This is a minor field that just allows users to hide the default icon if they want but there are other ways to do that now.
