### ISSUE TITLE
[Feature Request]: Reexposing groups and statuses like `is_pinned`.

### ISSUE THREAD

**Issue by cenk1cenk2** [akinsho/bufferline.nvim#736]
### What?

Hello @akinsho,

Thank you for maintaining this plugin for such a long time.

With the latest changes, `"bufferline.groups"` no longer expose the groups for manipulation/look-up except for testing. If it is not much of a hassle can these be reexported?

I might be missing the other way to implement this but thank you so much for your time either way.

### Why?

I know this is the internal API of the plugin but I have been [heavily using it](https://github.com/cenk1cenk2/nvim/blob/b5b99a8f170119d953a297f3e44624b77dcd6072/lua/extensions/bufferline-nvim.lua#L234) to implement functionality like closing all buffers but current except for the pinned ones, maybe that would be the case for others too.

These use cases like closing all but current were discussed in an issue before and you have indicated that this is easily implementable. Still, with the API no longer exposing them, it is impossible to do so anymore.

**Comment by akinsho** [comment]
Hi @cenk1cenk2,

That's a really unfortunate feature/behaviour of lua that I can't hide private implementation details. I would have/strongly advise against using the internal APIs like this. Unfortunately it ties my hands way too much to have to worry about breaking users configs if they are using things I haven't explicitly exposed.

I think as a general rule to maintain my sanity if a module isn't documented as exposed it should be treated as private and I will tweak those things as needed. So I don't want to revert this since one of the reasons I changed this was because I didn't want these things exposed by accident so people wouldn't use them. Going forward I will actively actually try to hide anything that I can since I really don't want the internal of this plugin exposed by accident.

That being said I open to providing public APIs for achieving some *common/valuable* features.
In this case I'm not sure precisely watch feature/API *exactly* is missing. You shouldn't be manually manipulating groups I think this is a huge problem internally (as I've described).

Maybe you can list out *what functionality you are trying to achieve* then I can think of if it's easy/possible etc.

It's important not to focus on the internal API but on the functionality you want since ultimately a lot of the internals can and will change over time definitely.

**Comment by cenk1cenk2** [comment]
Hey @akinsho,

Thank you for your time and detailed answer. I do 100% agree on keeping private things private as you said and fully support the changes.

In my case, I do only need to know if a certain buffer with a number is in a certain group. I suppose that can be a useful feature if anybody has implemented a functionality like me closing everything unless they are pinned.

I suppose this has been discussed many times before like https://github.com/akinsho/bufferline.nvim/issues/580, https://github.com/akinsho/bufferline.nvim/issues/309, therefore, might be worthy of the public API.

**Comment by akinsho** [comment]
@cenk1cenk2 there is already a command called `BufferlineGroupClose` which you can use to close any group, would this problem be solved by being able to specify multiple groups?

The reason I closed those other issues is that users have been trying to nudge this plugin into doing buffer management but I've explained many times that the object of this plugin is UI it's not a tool designed for buffer management

**Comment by akinsho** [comment]
I guess you could add a new class to group close but with an `except=pinned` a flag that could be used to invert the behaviour

**Comment by cenk1cenk2** [comment]
To be honest, the only thing that can solve my use case is to have a function that can check whether the buffer is certain group. I have missed the commands like `BufferlineGroupClose` at the time I have implemented this, so thanks for the heads up since I now know I can implement some of the functions I have without doing any trickery.

But with that said I sincerly thank you for taking your time and very grateful for all the answers as well as if you do not see it fit to have this on the public API, I still totaly understand that since it can be a very specific use-case that does not comply with having a clean way to manage buffers.

**Comment by akinsho** [comment]
So I think I still misunderstand the use case because it sounds like you just want to be able to close all buffer not inside of a group e.g. close all unpinned buffers. This should be easy enough by changing the `GroupClose` command to do something like `GroupClose except=pinned` this would basically allow any buffer in that group to say open and close all the rest.

It seems like this would solve your issue? why do you think you'd still need a function to manually check the groups?

**Comment by cenk1cenk2** [comment]
Yeah I know realize that I use the archaic version of the API to try to achieve what I am doing. Thanks for the heads up @kasthor.

**Comment by akinsho** [comment]
So a lot of these use cases fall into the buffer management plugin space which I often find there are already enough solutions for in other plugins or natively.

Some examples of good plugins that solve buffer management well already are:
* https://github.com/moll/vim-bbye
* https://github.com/ojroques/nvim-bufdel
* https://github.com/kazhala/close-buffers.nvim

For example close all but current gets mentioned a lot but neovim already has a pretty simple solution for a basic version of this which is

```
	vim.keymap.set('n', '<leader>on', [[<cmd>w <bar> %bd <bar> e#<CR>]], { desc = 'close all other buffers' })
```

The complex combination of close all that aren't pinned except the current one I think is outside the realm of general enough to add to the plugin this seems like something quite specific to a workflow and not generally applicable.

In general to clarify the only buffer "management" commands in this plugin only exist because they operate through or on something that only this plugin is aware of/created e.g. groups, this is the requirement for it being added to this plugin, it solves a problem that only this plugin can solve (which is often because it's a paradigm created by this plugin).

Anyway the TLDR is, some sort of `except=<group-name>` seems like a good addition to me, any more specific use cases on top of that seem like they stray into basically taking on the extra work of buffer management.

**Comment by akinsho** [comment]
@kasthor your snippet/desired functionality can be achieved *entirely without bufferline existing or being involved* e.g.
```lua
for _, id in ipairs(vim.api.nvim_list_bufs()) do
  if vim.api.nvim_buf_is_valid(id) then
    -- you can do whatever you want based on 
    -- vim.bo
    local modified = vim.bo[id].modified
    local buftype = vim.bo[id].buftype
    local filetype = vim.bo[id].filetype
    local name = vim.api.nvim_buf_get_name(id)
    if predicate_i_want then
      vim.api.nvim_buf_delete(id, { force = true})
    end
  end
end

```

**Comment by Gremious** [comment]
With the future addition of the `except=` argument, I'd like to kindly ask for an example - how would a "close all but current or pinned" function look like?

I am also one of the people who would really like to be able to do this, I often want to close all my tabs except the one I'm currently editing, and without losing all my pinned ones.

**Comment by bruce3x** [comment]
@Gremious  
I am using this function to close other buffers without pinned.

```lua
function()
  local bufferline = require("bufferline")
  local commands = require("bufferline.commands")
  local current = vim.api.nvim_get_current_buf()
  vim.schedule(function()
    for _, e in ipairs(bufferline.get_elements().elements) do
      local is_current = e.id == current
      local is_pinned = bufferline.groups._is_pinned(e)
      if not is_current and not is_pinned then
        commands.unpin_and_close(e.id)
      end
    end
  end)
end
```

**Comment by cenk1cenk2** [comment]
Thank you for your time on this, I would just close this to reduce clutter.
