### ISSUE TITLE
Feature request: Keep files sorted

### ISSUE THREAD

**Issue by hacker-DOM** [akinsho/bufferline.nvim#748]
N00b question: is it possible to keep files (buffers) sorted in the buffer line?

**Comment by akinsho** [comment]
Hi, I'm not sure I understand my question. There are several sorting strategies and generally the buffers will stick with whatever strategy was chosen. So in that sense by defaults there will maintain the sort order. If you mean persist them over time then you can persist them between neovim sessions if you happen to move them yourself. Otherwise they will be resorted when you restart a session

**Comment by akinsho** [comment]
Hi, I'm not sure I understand my question. There are several sorting strategies and generally the buffers will stick with whatever strategy was chosen. So in that sense by defaults there will maintain the sort order. If you mean persist them over time then you can persist them between neovim sessions if you happen to move them yourself. Otherwise they will be resorted when you restart a session.

I recommend going through the read me and using the plugin a little bit to see how it works and if there are still questions please try to formulate a specific one but in general the issue tracker is not a good place to ask questions as I don't have a huge amount of time to answer individual user questions
