### ISSUE TITLE
[Bug]: Background not rendering

### ISSUE THREAD

**Issue by ugoschieli** [akinsho/bufferline.nvim#753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Every other time the background of the bufferline is not displayed correctly
![Capture d'écran 2023-05-09 183809](https://github.com/akinsho/bufferline.nvim/assets/87332965/b152b454-89ad-4d9c-9f1d-2108b0a04049)

### What did you expect to happen?

Expected behaviour
![Capture d'écran 2023-05-09 183837](https://github.com/akinsho/bufferline.nvim/assets/87332965/8ccc7bbd-5344-45eb-80f2-5254c0d659ba)

### Config

return {
  {
    "akinsho/bufferline.nvim",
    dependencies = { 'nvim-tree/nvim-web-devicons' },
    config = function()
      require('bufferline').setup({
        options = {
          show_buffer_close_icons = false,
          show_close_icon = false,
          show_buffer_icons = false,
          modified_icon = '',
          indicator = {
             style = 'none'
          },
        }
      })
    end
  }
}

### Additional Information

I'm using Alacritty on WSL2

**Comment by akinsho** [comment]
@ugoschieli this configuration works fine for i.e. I am able to see the background without issue. Please (please) try to reproduce these sort of bugs with a minimal `init.lua` this is most likely due to another plugin or configuration issue. If you are able to reproduce this with a config that contains nothing else except a bufferline, and a colorscheme and you can verify that it isnt' exclusively a problem of that one colorscheme then please repost and I'll re-open
