### ISSUE TITLE
[Feature Request]: Full border bufferline

### ISSUE THREAD

**Issue by AethesticCoder** [akinsho/bufferline.nvim#755]
### What?

it will be nice if it is possible to achive something like this:

![vscode - copia](https://github.com/akinsho/bufferline.nvim/assets/70770072/5c97feca-b0e7-45ca-a853-f038998afb87)

edit: ignore the gradient i only want the full border and the padding between buffers

### Why?

this is for aesthetic and for have a beatiful editor

**Comment by akinsho** [comment]
@AethesticCoder this isn't possible currently in neovim because the bufferline can only be one cell tall. In the example you show here the bufferline would actually need to be at least 3 cells high which just isn't possible today. I've personally wanted to implement something kind of similar, maybe one day with the externalisation of neovim plugin authors/users will be able to set the height of the tabline but I don't see that coming soon

**Comment by AethesticCoder** [comment]
Ok I understand, so this is something more related to nvim repo and the way the buffer are display

**Comment by AethesticCoder** [comment]
Ok I understand, so this is something more related to nvim repo and the way the buffer are display

**Comment by akinsho** [comment]
@AethesticCoder I can't do a whole exposition on how the terminal and neovim work together that you'll need to do some research for but in short neovim in the terminal is a grid of squares each line of text is one row of cells. Currently only one row of cells is allocated for the statusline or the tabline. Neovim won't change the way tabs look it isn't really their job to add things like borders to the tabline or rather they just won't. A plugin could do it but you would need more space than a single row of cells.
