### ISSUE TITLE
[Feature Request]: edgy.nvim support

### ISSUE THREAD

**Issue by folke** [akinsho/bufferline.nvim#770]
### What?

Hi!

I just released a new plugin [edgy.nvim](https://github.com/folke/edgy.nvim).

It enforces windows to a pre-defined layout of sidebars and panels.

To make the plugin work properly with bufferline offsets, I currently patch the `offset.get` code as you can see here https://www.lazyvim.org/plugins/extras/ui.edgy#bufferlinenvim

I'm willing to work on a PR, but I was wondering how you would prefer this to work?

Thanks

**Comment by akinsho** [comment]
Hi @folke,

I'm on holiday for the next few weeks but in general I'm open to integrations but I'd rather expose some sort of API if possible rather than hard coded support for specific plugins. I haven't really looked at the plugin or integration you linked so not sure what shape the API would take though

**Comment by folke** [comment]
Yeah, I wou'dn't hard-code an intergration indeed. I'll see if I can come up with something as a start. We can take it from there once you're back from holiday. Enjoy!
