### ISSUE TITLE
close current buffer

### ISSUE THREAD

**Issue by tinysss** [akinsho/bufferline.nvim#775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

 :BufferLinePick<CR>     or     :bd <return> 
 other buffers  fail to display correctly.

### What did you expect to happen?

display correctly.

### Config

 vim.api.nvim_set_keymap("n", "gb", "<Cmd>BufferLinePick<CR>", {noremap = true, silent = true})

**Comment by akinsho** [comment]
Your config doesn't appear to be correct because you haven't added the mapping correctly. Adding a mapping command should look like `<Cmd>BufferLinePick<CR>` not just writing `BufferLinePick` also the issue isn't very clear but you can just use `:bd` so I don't think bufferline needs to do anything here
