### ISSUE TITLE
[Bug]: v3.6.0 broke the close sign

### ISSUE THREAD

**Issue by amanvm** [akinsho/bufferline.nvim#783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The close sign worked well in v3.5.0 (or earlier) on iTerm2, but since v3.6.0, it appears broken. Copy-pasting the sequences reveals they are actually different sequences too. Doesn't matter what font I use. The first image is for v3.5.0, and second if for the latest v4.2.0 (the same effect is seen first on v3.6.0)

<img width="181" alt="Screenshot 2023-07-04 at 4 21 57 PM" src="https://github.com/akinsho/bufferline.nvim/assets/25681815/93a7bcc3-652e-4cb7-983b-ce2da3e1f247">

<img width="181" alt="Screenshot 2023-07-04 at 4 17 26 PM" src="https://github.com/akinsho/bufferline.nvim/assets/25681815/e0ccf3b6-ff34-4058-9cac-ed190076a478">

### What did you expect to happen?

Close sign should work irrespective of bufferline version!

### Config

My config doesn't change any icons

### Additional Information

System: macOS Ventura 13.4.1 (22F82)
Terminal: iTerm2
Shell: zsh 5.9

**Comment by akinsho** [comment]
@amanvm several months ago nerd fonts updated their icons this was a breaking change that affect all nvim plugins using icons. I updated the icons to replace the now broken icons. This means anyone who has not updated their font will have this breakage. You can either
a) update your nerdfont to the latest version
b) replace the close icon with the outdated font icon that was used previously

In either case this isn't quite a bug but a breaking change of an external terminal level dependency that I cannot control and must conform to.

**Comment by edsu** [comment]
I'm pretty certain I've downloaded the [latest Inconsolata NerdFont](https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/InconsolataGo.zip), installed it in `~/Library/Fonts/` and refreshed my cache. I still see a missing icon for closing the tab:

<img width="1392" alt="Screenshot 2023-07-17 at 12 56 00 PM" src="https://github.com/akinsho/bufferline.nvim/assets/33829/32f51683-8258-4b28-8dc3-278347a2df3b">

Looking at the [v3.0.2 release notes ](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.2) makes me wonder if something was changed back?

**Comment by akinsho** [comment]
Hi @edsu, looking through those release notes it doesn't really look like anything was reverted just a few bugs in specific fonts. The path I used to update the fonts was the one laid out by the maintainers of nerd fonts i.e. I used nerdfix which highlighted the previous close icon as deprecated. AFAICT the issue of getting the right fonts and making sure it's all loaded correctly in the terminal is a somewhat onerous and very specific to each individuals situation so I think not something for this plugin to fix.

I think https://github.com/ryanoasis/nerd-fonts/blob/master/bin/scripts/test-fonts.sh is a script to test that your font works but in general I don't think there's yet any reason to think that this issue is specific to this plugin rather than nerd font/terminal update issues

**Comment by edsu** [comment]
@akinsho I guess it shouldn't matter but which specific NerdFont do you use?

**Comment by akinsho** [comment]
@edsu I use the symbols only font with kitty and non patched font as the main font. It's a little complicated so not the best example. In either case the symbol only font is just all the nerd font symbols in a separate font.

**Comment by dlaub3** [comment]
In my case I had the latest fonts installed but this issue did not resolve until after I delete the plugin from disk and reinstalled.
