### ISSUE TITLE
[feature request] highlight the entire buffer background

### ISSUE THREAD

**Issue by andreicorpo** [akinsho/bufferline.nvim#79]
Hi! 

First of all, thank you for this awesome plugin! 

I am wondering if it is possible to highlight the entire background of a buffer  when it has any errors, warnings, infos or any diagnostics. 

From what I have tried, I succeded in having a entire background color if the buffer has no errors and so on by setting `buffer_selected`, `indicator_selected` ... 

But when an error appears in the buffer, only the filename's bg changes color.

So I was wondering if something like `buffer_selected_all`, `error_selected_all` would be possbile.

Thanks again for this awesome plugin! 😁

**Comment by andreicorpo** [comment]
Sure! I'll give it a try this weekend. Hopefully.

**Comment by akinsho** [comment]
I'm going to close this out since it's been open for months and there are no takers. Frankly I don't love the complexity it would bring but will review a PR if someone else wants to still contribute this change. Alternatively there are quite a few other bufferline plugins with different UI that aim to support this type of thing out of the box so 🤷🏿‍♂️
