### ISSUE TITLE
[Feature Request]: Can i close buffer by number?

### ISSUE THREAD

**Issue by AlanLang** [akinsho/bufferline.nvim#791]
### What?

I am trying to find a way to close buffers based on their numbers. Unfortunately, I have been unable to locate a specific functionality or configuration option to achieve this. I have thoroughly reviewed the documentation and explored the available settings, but I couldn't find a solution.
I would like to inquire whether there is a built-in feature or a recommended approach to close buffers based on their numbers in bufferline.nvim. If such functionality does not currently exist, I would like to request it as a potential enhancement for future releases.

### Why?

I can only use `BufferLinePickClose` to close a specific buffer, but this method is not very efficient. It would be much more convenient if I could directly close a specified buffer using its number.

**Comment by akinsho** [comment]
Hi @AlanLang so closing buffers and really managing buffers is not a goal of this plugin. The main goal of this plugin is _visualising_ buffers. There are many great plugins designed for closing buffers and plenty of native functionality e.g. `:bdelete mybuf.txt`. I recommend using one of these mechanisms rather than relying on bufferline here.

**Comment by akinsho** [comment]
For what it's worth there are some commands documented in the help docs e.g. bufferline close. But the native functionality also works
