### ISSUE TITLE
[Ques]: How to not show bufferline indicator for specific buffer name.

### ISSUE THREAD

**Issue by niksingh710** [akinsho/bufferline.nvim#809]
e.g `[Command Line]`

as i use `q:` in place of `:` everytime i press `:` bufferline shows me a buffer entry with name `[Command Line]` 

is there any way to not show that specific buffer entry at the moment?

**Comment by akinsho** [comment]
@niksingh710 a buffer for the command line is opened so the behaviour is technically correct. I don't have an immediate idea of how to avoid it and tbh this is too specific a use case to incorporate into the plugin

**Comment by niksingh710** [comment]
I agree the use case is too specific.
but i was expecting if there will be an option something like `ignore_filetype = {}`

**Comment by akinsho** [comment]
@niksingh710 bufferline is a global setting so having a filetype option doesn't really make sense since you could have like 20 buffers open with different filetypes having it flicker in and out isn't an option IMO but you can already do this yourself using `showtabline` and a filetype autocommand in your config
