### ISSUE TITLE
[Bug]: Error when using mode = buffers

### ISSUE THREAD

**Issue by alienxp03** [akinsho/bufferline.nvim#811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I'm getting an error when I start `neovim`: `(UNKNOWN PLUGIN): Error executing lua: attempt to call a number value`.
This only happens when I set `mode = "buffers"`. If I use `mode = "tabs"`, there's no error during startup.

<img width="1244" alt="Screenshot 2023-09-07 at 3 09 43 PM" src="https://github.com/akinsho/bufferline.nvim/assets/672704/22540fd3-efb2-4ce2-9f11-38eb9fca2a22">

### What did you expect to happen?

It should not show any error when I set `mode = "buffers"`

### Config

```lua
return {
  "akinsho/bufferline.nvim",
  dependencies = { "nvim-tree/nvim-web-devicons" },
  version = "*",
  opts = {
    options = {
      mode = "buffers",
      separator_style = "thin",
    },
  },
}
```

### Additional Information

- bufferline: 4.3.0
- neovim 0.9.1

**Comment by alienxp03** [comment]
Is there a way to see the logs produced by bufferline for the issue? My setup is not minimal, but `nvim-tree` is not an uncommon plugin too. From [bufferline docs](https://github.com/akinsho/bufferline.nvim/blob/main/doc/bufferline.txt#L585), I assume that it should work by default with `nvim-tree` as well considering my bufferline setup is pretty basic.

**Comment by akinsho** [comment]
@alienxp03 it should work with nvim-tree and I used that plugin for years without issue. There are no logs, please try debugging your config using the strategy of minimal init.lua and adding things until the problem recurs. You can also check the issues for a previous one that shows a similar error as someone has definitely reported this before and it turned out to be a config issue and related to another plugin.

I cannot help each individual person debug their config, I already spend most of my mornings before work triaging issues. Unfortunately it will be up to you to debug and investigate your config yourself. If you run only this plugin with a clean neovim config you will find that this issue is not present

**Comment by akinsho** [comment]
If you search literally for the error you found the first issue that comes up is the previous one https://github.com/akinsho/bufferline.nvim/issues/786 (not sure what your search included).

The error you are seeing is `virtual text` spit out by neovim core as it doesn't have a better way of handling that type of error.

Trying to add a log to find where this is coming from is a monstrously difficult task, "adding logs" in the context of neovim is no where near as straightforward as it might seems since any plugins can throw any errors at any point in their own code which is where this comes from as there is literally no reference to this error anywhere within this plugin
