### ISSUE TITLE
[Bug]: how to config adaptive tab size?

### ISSUE THREAD

**Issue by yimingwangdell** [akinsho/bufferline.nvim#825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

as titled

### What did you expect to happen?

describe how to config it in help.

### Config

Any

### Additional Information

...

**Comment by akinsho** [comment]
Not entirely sure what this issue is trying to describe, in general the issue tracker is not a good place for usage questions. As far as I can discern from your question there is no such thing as adaptive tab size in this plugin which is why there is no mention of it in the help. The plugin ensures that in general all tabs are similarly sized, there is no way for them to each have their own random size based on the content. That was an explicit design decision I made when creating this plugin
