### ISSUE TITLE
Add separator in last item as an option

### ISSUE THREAD

**Issue by agnjunio** [akinsho/bufferline.nvim#835]
My current style requires the separator to be shown at every item:

![image](https://github.com/akinsho/bufferline.nvim/assets/13356774/220a26d8-6f43-49e0-ae85-cc82492e1c09)

However, when I'm at the last item, separator is not shown:

![image](https://github.com/akinsho/bufferline.nvim/assets/13356774/4648b13b-6558-4e70-a998-2b3aaf449bba)

My separator:
```
separator_style = { "", " " },
```
So by changing here we could have an option to allow the last separator if it's a custom separator like i'm using: 

https://github.com/akinsho/bufferline.nvim/blob/9e8d2f695dd50ab6821a6a53a840c32d2067a78a/lua/bufferline/ui.lua#L406

**Comment by akinsho** [comment]
@agnjunio, this plugin is purposely fairly opinionated and IMO has too many options making maintenance generally an increasing burden. Tbh I really am not keen to take this on since frankly by the time you are tweaking the styling this much I think you are better suited using something `heirline.nvim` or one of the other much more configurable plugins. This plugin is largely intended as a sort of plug and play thing where you accept in general the styling with one or two tweaks but if the tab layout is something you want to be much different I think digging into a customisable plugin for this is better
