### ISSUE TITLE
[Feature Request]: Ability to close the current buffer with key binds 

### ISSUE THREAD

**Issue by Rehan-shah** [akinsho/bufferline.nvim#844]
### What?

I want to close the current buffer with key binds instating of going up clicking x

### Why?

this would increase my productivity 
I think it might there , but I can't find . If anyone could help that would also be great

**Comment by akinsho** [comment]
@Rehan-shah bufferline doesn't provide any specific commands to close the current buffer because neovim already has many commands for this sort of thing, including closing the window or deleting the buffer (`:bdelete`). Additionally, there are also lots of plugins that provide commands for buffer closing. In short this isn't something that I think needs to be managed in this plugin and you should look into any of the numbers blog posts or documentation about how to close the current buffer that can be adapted to use key binds

**Comment by lesar** [comment]
I have done this key binding and seems work: 
 .config/lvim/config.lua
```
lvim.keys.normal_mode["<leader>bx"] = ":lua lvim.builtin.bufferline.options.close_command()<CR>"
```
best regards
Leonardo
