### ISSUE TITLE
[Bug]: Keyboard interrupt

### ISSUE THREAD

**Issue by kapral18** [akinsho/bufferline.nvim#850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![CleanShot 2024-01-09 at 20 24 59](https://github.com/akinsho/bufferline.nvim/assets/1625373/af953054-0ee7-4a64-b009-fa02964c4ec0)

During regular nvim-cmp completionj

### What did you expect to happen?

No error

### Config

https://github.com/kapral18/config.nvim/blob/23d158436714444648144c8bcd53d0a0554d1c73/lua/plugins/bufferline.lua

### Additional Information

...

**Comment by akinsho** [comment]
I use and have used cmp for years with bufferline at this point without this issue. I'll need clear reproduction steps that definitively show that bufferline is the issue to reopen this

**Comment by kapral18** [comment]
@akinsho I put config because you requested to put config in your issues template. There is no field that says minimum viable example. Having said that I'd still provide it nevertheless had I have it. The whole idea with this bug is that I have no clue why it happens, hence I cannot reproduce it. It happens randomly. And when it happens all I have is an error with a trace to get_buf_count function. I was hoping it would already be a hint.

**Comment by akinsho** [comment]
@kapral18 I really do not have a huge amount of time to dedicate to the maintenance of this and several other plugins I manage. Many people report issues that they don't provide reproduction steps for. To be this is a non starter as I then spend several hours on one plugin and one issue only to discover it was something in the users config 9/10. This might not be ideal for you but given the time I have it's all I can do. So I need a few lines of lua config that help me recreate it locally so I can see it quickly. The error you reported in the issue is hard to read from just a screenshot not even the stack trace but it doesn't point to anything.

**Comment by kapral18** [comment]
@akinsho I never asked for immediate attention for this or put any timeframe on you. So no need to get this defensive. I appreciate your work on this plugin and again had I a better repro I'd have added it in the first place. The idea behind opening an issue since you don't have a discussion section was to share it so that either author or others who have faced this problem could elaborate if they have better repo. Or maybe from the stack from screenshot you could already tell where this comes from. This has already happened many times successfully on other issues and threads from other projects. From your answer I understand that's not the case already, which is fine. I don't have a problem with the issue being closed, I don't have high expectations. If I manage to get it better reproduced I will post it here or will debug it myself and suggest a PR. Cheers.
