### ISSUE TITLE
[Feature Request]: Add buttons to buffers

### ISSUE THREAD

**Issue by gacallea** [akinsho/bufferline.nvim#854]
### What?

Hi,

I've searched this repo and the internet far and wide, the only similar issue I found is: https://github.com/akinsho/bufferline.nvim/issues/183

I was wondering if it's possible to add clickable buttons to each buffer/tab? Like the custom area allows on the bufferline, but for each buffer instead? Is it possible to add those buttons to appear on the right of each buffer and add functions to them? Possibly for a specific filetype only?

The screenshot shows the buttons in the custom area, but I'd like the same buttons to be on each open .ck buffer where the diagnostic usually show. This won't be an issue with `.ck` as there is no LSP (probably never will).

<img width="732" alt="Screenshot 2024-01-24 at 9 48 07 AM" src="https://github.com/LazyVim/LazyVim/assets/3269984/d5da773f-d1da-494a-bdbf-fd8f56c65e6a">

I looked at the code trying to understand if it was possible to _hijack the code_ that shows diagnostic in the same area, to have buttons instead, but I haven't found a way.

Please and thank you

### Why?

The plugin I'm developing could use this feature that needs specific actions tied to the buffer: https://github.com/gacallea/chuck-nvim/issues/9

I'm aware this is a very specific issue and that is probably not falling under your intentions as explained here: https://github.com/akinsho/bufferline.nvim/issues/307 -- In that case, my apologies and a request to take it as a question, more than anything else.

Please and thank you

**Comment by akinsho** [comment]
Hi @gacallea

So it's an interesting idea and probably possible with new functionality, definitely not possible as is. Much like there are other modules for diagnostics etc. I guess one could be added for this. Personally I think this is way too niche for the complexity it would introduce but one thought I have if you are willing to go down that rabbit hole yourself is custom areas within each buffer tab. Similar to how the custom areas at the end work I guess a similar if no the same logic could be applied but to each individual buffer.

Whilst not particularly complicated this will be fairly involved and will really require having a good deep look into the code base. It isn't something I could just point you towards unfortunately as you'd need to get to grips with the buffer rendering logic as well as the areas logic.

Once something like that is available you could then hook into it to render your custom button. Totally up to you since as far as I'm concerned it'd be too much work for me personally to be worth the trouble as I'd never use that tbh

**Comment by gacallea** [comment]
Hi @akinsho,

thanks for the timely and detailed reply, I appreciate. As much as I would like to contribute, I'm no Lua coder and the `chuck-nvim` plugin has taken me two weeks off my main studying already. I did the plugin with absolute zero knowledge of nvim plugins and lua development. I could be happy with what I have achieved so far, and the buttons would be icing on the cake at this point in time.

That said, perhaps I could try to tackle this in the future, but it's not something I can afford right now.

Thank you for bufferline and all you do, I appreciate you :)
