### ISSUE TITLE
[Bug]: Error executing lua ...ker/start/bufferline.nvim/lua/bufferline/diagnostics.lua:75: attempt to call field 'is_enabled' (a nil value)

### ISSUE THREAD

**Issue by Johan-Liebert1** [akinsho/bufferline.nvim#908]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The issue is that... this error occurs, then the buffer line disappears leaving only one tab visible

### What did you expect to happen?

Expected behaviour. Should not happen

### Config

require("bufferline").setup({
    options = {
        mode = "buffers",
        diagnostics = "nvim_lsp",
    },
})

### Additional Information

Happened after I updated the plugin. Usually triggers when I do `gF` to goto a file, but doesn't happen consistently.
This commit 2cd39842c6426fb6c9a79fa57420121cc81c9804 is the culprit most probably. Maybe not backwards compatible with v0.9.5? 

Here is my neovim version info

```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### commit

2cd39842c6426fb6c9a79fa57420121cc81c9804

**Comment by akinsho** [comment]
@Johan-Liebert1 you need to update your version of neovim to `0.10.0` I'm getting a lot of bug reports because quite a few APIs were deprecated and it's proving a nightmare to keep things stable on everyone's versions so I'm going to have to officially move the required version for this plugin to `0.10.0` for simplicity

**Comment by Johan-Liebert1** [comment]
Ah, okay. I've pinned my plugin to a previous commit for now. Thanks for the reply

**Comment by Grazfather** [comment]
I am hitting this despite your check for nvim 0.10.0. That is because this isn't present in my 0.10.0-dev version.

Maybe instead of testing for a version, you could directly test for the feature? e.g. you could probably do `if vim.diagnostic.is_enabled ~= nil`

**Comment by akinsho** [comment]
@Grazfather seems like rather than working around it it's a neovim bug that a version check is failing? If you're on v0.10.0 and it's not acknowledging that this seems like it'll be an issue for a lot of people and plugins

**Comment by Grazfather** [comment]
It is acknowledging that I am on v0.10.0, but i happen to be on a version of v0.10.0 that doesn't have all the versions of the full release. I am inclined to agree that it's probably a neovim bug if it says that it's some version when it's a prerelease of it.

That said, it's still probably best/easiest to just test for the existence of features before using than, rather than maintaining some set of functionality behind version gates, no?

**Comment by Grazfather** [comment]
This hasn't been fixed and I just hit it again, searched it, and found this ticket.

For future me or anyone else, I work around it:

```diff
diff --git a/lua/bufferline/diagnostics.lua b/lua/bufferline/diagnostics.lua
index e6ffdc3..eac3573 100644
--- a/lua/bufferline/diagnostics.lua
+++ b/lua/bufferline/diagnostics.lua
@@ -68,12 +68,12 @@ local function is_insert() -- insert or replace
 end

 local function diagnostic_is_enabled(d)
-  if vim.fn.has("nvim-0.10") == 1 then
-    return vim.diagnostic.is_enabled({ ns_id = d.namespace, bufnr = d.bufnr })
-  else
+  -- if vim.fn.has("nvim-0.10") == 1 then
+  --   return vim.diagnostic.is_enabled({ ns_id = d.namespace, bufnr = d.bufnr })
+  -- else
     -- neovim 0.9.x
     return not (vim.diagnostic.is_disabled and vim.diagnostic.is_disabled(d.bufnr, d.namespace))
-  end
+  -- end
 end

 local get_diagnostics = {
```

though it would still probably be better to fix this plugin to check `if vim.diagnostic.is_enabled ~= nil` than just say it's a bug in neovim.
