### ISSUE TITLE
[Bug]: indicator highlight takes no effect

### ISSUE THREAD

**Issue by PhoenixPtt** [akinsho/bufferline.nvim#910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

indicator highlight setting takes no effect

### What did you expect to happen?

indicator fg and bg display what i have set

### Config

				indicator_visible = {
					fg = "#FF0000",
					bg = "#FF0000",
				},
				indicator_selected = {
					fg = "#FF0000",
					bg = "#FF0000",
				},

**Comment by akinsho** [comment]
@PhoenixPtt I often issues raised about highlights not working the majority of these are due to misconfigurations. As I've just come back from holiday and have like 40+ issues pending I'm going to close this with the assumption that it is a similar type of issue. None of the highlight groups have changed in close to a year so I don't imagine that this is actually broken at the code level is more likely an issue of how it is being set. Unfortunately I don't have time to help debug this as I barely have time for all these new issues

**Comment by PhoenixPtt** [comment]
thanks for your prompt reply. perhaps my discription is not clearly, so i want to say it again.
1. i set a indicator as below:
![image](https://github.com/akinsho/bufferline.nvim/assets/68508116/ba4fdd53-283b-4492-b56d-efa05ca24f7a)

2. bufferline shows like this:
![image](https://github.com/akinsho/bufferline.nvim/assets/68508116/1e308b03-6fdd-4922-862a-83a0434be9f6)

3. then i set the fg and bg,:
![image](https://github.com/akinsho/bufferline.nvim/assets/68508116/eda60486-83b0-4640-9e64-f1676818d127)

4. 5. but nothing happens, i want to know whether i have chosen the right option?
