### ISSUE TITLE
[Bug]: not working when load before other plugins

### ISSUE THREAD

**Issue by nfwyst** [akinsho/bufferline.nvim#934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

there is no buffer tab show when i use lazy = false or priority = 1000 in lazy.nvim

### What did you expect to happen?

show buffer tab

### Config

```lua
{
  "akinsho/bufferline.nvim",
  lazy = false,
  priority = 1000,
  -- event = { "BufReadPost", "BufAdd", "BufNewFile" },
  dependencies = { "nvim-tree/nvim-web-devicons" },
  config = function()
    local bufferline = require("bufferline")
    bufferline.setup()
  end,
}
```

### Additional Information

nvim version: 0.10

**Comment by akinsho** [comment]
@nfwyst since I can confirm that the plugin definitely works and no other users are reporting issues this is almost certainly a configuration issue. Unfortunately I'm stretched way too thin to help debug config issues, sorry. Please have a close look at lazy.nvim docs and maybe some other peoples dotfiles
