### ISSUE TITLE
[Feature Request]: Add `global` to `vim.o.sessionoptions` automatically (if `persist_buffer_sort` is True)

### ISSUE THREAD

**Issue by richardso21** [akinsho/bufferline.nvim#969]
### What?

If `persist_buffer_sort == true`, then before setting up the auto command we should also check to see that `global` is in `sessionoptions`. If not, we should insert it.

This also brings up the edge case where pinned buffers won't persist if `persist_buffer_sort == false`. In that case, we can make this functionality togglable as well and insert `global` if either one is true as specified in the `config` table. 

We could also just ignore all of this and insert `global` into session options during plugin setup, regardless of the config options.

### Why?

There are already multiple issues in the past (#660, #649) where people have forgot to add `global` into session options. I admit that it took me a while to pinpoint this problem as well, and technically this is written in the help/doc file at the end of the section. However, the readme file implied that buffer order persists out-of-the-box, yet that's not entirely the case. I personally care about the ordering of my buffers (that's why I chose this plugin in the first place), so I think setting `sessionoptions` within the plugin would prevent future users from struggling with this.

If it's decided that no code changes would result from this issue, I suggest at least moving the disclaimer to the README just so others see this more clearly. 

Thanks!

**Comment by akinsho** [comment]
@richardso21 I *definitely definitely* do not want this plugin affecting peoples session files for a bunch of reasons, not the least of which is the expected mountain of issues from people custom setups. Re. moving it to the README tbh I think the number of things that would warrant a mention exactly because it affects someone use case is pretty huge which lead to me having to rewrite the readme to move all such knowledge to the help docs anyway.

The README is a glitzy description of the plugin, not where people are supposed to look for detailed instructions on how it works

**Comment by richardso21** [comment]
Fair enough, I totally understand

The readme does mention this right below the Re-ordering section:

> This order can be persisted between sessions (enabled by default).

I think adding something like "...(enabled by default, _once you add `globals` to `sessionoptions`_)" is minimal, yet helpful enough. Also, there are already a few places in the readme with **NOTES**, and I think a "gotcha" like this kinda fits as one of those.

Ultimately, it's your plugin repo though 😅 (which is awesome btw). If you still think otherwise, I'm fine to close this issue
